### ISSUE TITLE
Error Coming in compilation like "ain.c:1:22: warning: extra tokens at end of #include directive\n"

### ISSUE THREAD

**Issue by nitincoolsharma** [judge0/api#1]
My Code is this what changes I have to do for successful compilation.

#include <stdio.h>
int main()
{
	int a = 10;
	int b = 20;
	printf("a %d",a);
	return 0;
}

**Comment by hermanzdosilovic** [comment]
You are trying to compile this code:
```
#include <stdio.h> int main() { int a = 10; int b = 20; printf("a %d",a); return 0; }
```

I can't compile this either. It fails even on my PC when I save this to some file `test.c` and try compiling it `gcc test.c`.

My guess is that `#include <stdio.h>` should be in one line:
```
#include <stdio.h> 
int main() { int a = 10; int b = 20; printf("a %d",a); return 0; }
```

**Comment by nitincoolsharma** [comment]
Thank You @hermanzdosilovic  .
So I have to send "\n" between main and header file.
