### ISSUE TITLE
Request for having fixed language Id

### ISSUE THREAD

**Issue by JohnPremKumar** [judge0/api#106]
In a scenario, when the new version of the existing language need to be added. Then, it is inserted in between which changes the id of the languages which are present after the newly added language.

So, it will be better if the language id remains fixed even when above mentioned scenarios occur.

For achieving this, we can group the different versions of the same language with a common prefix like "A1" for python v2.4.0, "A2" for python v2.6.9 and so on.

Other ways of achieving the above mentioned results are also welcomed

**Comment by hermanzdosilovic** [comment]
Hi @JohnPremKumar,

as of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) languages can be archived thus they are preserved in the database but cannot be used.

This solves a problem you mentioned. Take a look at the source code and `seeds.rb` for details.

BR,
Herman

**Comment by JohnPremKumar** [comment]
Hi @hermanzdosilovic, thanks for the update. By the way, if we need to use the languages from from archived.rb, can I move them to active.rb before deploying it.

**Comment by hermanzdosilovic** [comment]
No you cannot just move archived language to active because compiler/interpreter for that language is no longer installed in the new Docker Image.
