### ISSUE TITLE
#<Encoding::UndefinedConversionError: \"\\xE2\" from ASCII-8BIT to UTF-8>

### ISSUE THREAD

**Issue by anarmammad** [judge0/api#107]
Hi, 
I have tried to test API with the sample data which was given in docs
`{
  "source_code": "#include <stdio.h>\n\nint main(void) {\n  char name[10];\n  scanf(\"%s\", name);\n  printf(\"hello, %s\n\", name);\n  return 0;\n}",
  "language_id": 4,
  "stdin": "world"
}`
and when i requested for submission result i got **Internal Server Error** - **#<Encoding::UndefinedConversionError: \"\\xE2\" from ASCII-8BIT to UTF-8>**

The attached file is the response for GET request.

[3423e748-3046-4eff-92c1-2d9fc7d7b518.txt](https://github.com/judge0/api/files/3666104/3423e748-3046-4eff-92c1-2d9fc7d7b518.txt)

Thanks in advance!

**Comment by hermanzdosilovic** [comment]
Hi @anarmammad,

as of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) you will get nice error description and instructions on how successfully get submission attributes.

BR,
Herman

**Comment by hermanzdosilovic** [comment]
I have made [asciicast](https://asciinema.org/a/318475) for additional help. Be sure to check it out.

**Comment by anarmammad** [comment]
@hermanzdosilovic Great! Thanks a lot!
