### ISSUE TITLE
install numpy for python3?

### ISSUE THREAD

**Issue by renaldoberkeley** [judge0/api#108]
Is it possible to install numpy library for python so that I can execute this code in the Dummy Client? 

![numpy_image](https://user-images.githubusercontent.com/42684662/66186083-267f2500-e636-11e9-8676-d33e9f394db6.PNG)

Also, is it possible to install matplotlib and show plots in Dummy Client?

**Comment by hermanzdosilovic** [comment]
You can also execute code in Judge0 IDE - https://ide.judge0.com. UI is much more intuitive.

Numpy is currently not available, but I can create a Docker image where it is installed, but you will have to deploy it for yourself.

It is not possible to get and show plots - you can only get text output.

**Comment by renaldoberkeley** [comment]
Ok thank you. Sure, if you create a docker image, I will try deploying myself.

**Comment by hermanzdosilovic** [comment]
What languages would you like to have in this Docker image? I can remove languages that you won't use in your project. What python libraries would you like to have?

**Comment by renaldoberkeley** [comment]
Hi Herman, thanks for the reply. For languages, lets go with Python 3.6 and Java 11. For python libraries, can you include libraries for data science, so numpy, scipy pandas, scikit-learn, pytorch, nltk, tensorflow, matplotlib, and seaborn. As you said, only text will show, however over time, I would like to tinker around with matplotlib and seaborn to see if I can get a simple plot to show. 

Thanks

**Comment by hermanzdosilovic** [comment]
@saikatharryc, none of the libraries are not part of the official Judge0 API releases.

Numpy won't be available as a preinstalled library on Judge0 API. It can already be available as specialized image.

**Comment by MariamQusai** [comment]
@hermanzdosilovic can we show plots using juge0?

**Comment by hermanzdosilovic** [comment]
Hi @MariamQusai,

Judge0 currently does not support the showing of the plots.

**Comment by Zhengrong34** [comment]
What is the image to fetch to include numpy that will be very helpful

**Comment by mattmascolo** [comment]
@hermanzdosilovic would you mind sharing a bit of direction on how to install our own libraries for selfhosted instances?

**Comment by freew01f** [comment]
> @hermanzdosilovic would you mind sharing a bit of direction on how to install our own libraries for selfhosted instances?

just edit the base image dockerfile 
add ur own lib and build
change it to ur project

**Comment by em-cloudsolutions** [comment]
> > @hermanzdosilovic would you mind sharing a bit of direction on how to install our own libraries for selfhosted instances?
> 
> just edit the base image dockerfile 
> add ur own lib and build
> change it to ur project

Is it possible for you to tell us the exact file name and where to put what?

That would be great!

**Comment by alishahzad789** [comment]
> > @hermanzdosilovic would you mind sharing a bit of direction on how to install our own libraries for selfhosted instances?
> 
> just edit the base image dockerfile add ur own lib and build change it to ur project

how would one do that can you guide please
