### ISSUE TITLE
<Redis::CannotConnectError (Error connecting to Redis on localhost:6379 (Errno::EADDRNOTAVAIL)): api_1     | api_1     | app/controllers/health_controller.rb:4:in `workers'

### ISSUE THREAD

**Issue by phuongHoang01** [judge0/api#109]
i spent the last 12 hours trying to fix a this error 
still dont know how to fix it can you help me pleaseeee
p/s i already set protected-mode no :<
![image](https://user-images.githubusercontent.com/53004236/66416649-79871c80-ea28-11e9-86d8-74eb20325b12.png)

**Comment by hermanzdosilovic** [comment]
Hi @phuongHoang01,

can you please tell me how your setup looks like? Are you trying dev or production setup? Do you use Docker?

**Comment by phuongHoang01** [comment]
Sorry for late reply
99% my config is default 

###############################################################################
# Rails Environment
###############################################################################
# Specify Rails environment: production or development
# Default: development
RAILS_ENV=

# Specify maximum number of concurrent Rails threads.
# Default: 5
RAILS_MAX_THREADS=

# Secret key base for production, if not set it will be randomly generated
# Default: randomly generated
SECRET_KEY_BASE= 

# Allow only specified origins. In development all origins are allowed and this
# cannot be overwriten. This configuration setting will only be used in
# production. If left blank, then all origin will be allowed (denoted with '*')
# Example:
# ALLOW_ORIGIN=www.judge0.com judge0.com www.example.com blog.example.com
ALLOW_ORIGIN=


###############################################################################
# Authentication
###############################################################################
# You can protect your API with (AUTHN_HEADER, AUTHN_TOKEN) pair.
# Each request then needs to have this pair either in headers or
# query parameters. For example let AUTHN_HEADER=X-Judge0-Token and
# AUTHN_TOKEN=mySecretToken. Then user should authenticate by sending this
# in headers or query parameters in each request, e.g.:
# https://api.judge0.com/system_info?X-Judge0-Token=mySecretToken

# Specify authentication header name.
# Default: X-Auth-Token
AUTHN_HEADER=

# Specify valid authentication tokens.
# Default: empty - authentication is disabled
AUTHN_TOKEN=


###############################################################################
# Authorization
###############################################################################
# Protected API calls can be issued with (AUTHZ_HEADER, AUTHZ_TOKEN) pair.
# To see exactly which API calls are protected with authorization tokens
# please read the docs at https://api.judge0.com.
# API authorization ensures that only specified users call protected API calls.
# For example let AUTHZ_HEADER=X-Judge0-User and AUTHZ_TOKEN=mySecretToken.
# Then user should authorize be sending this in headers or query parameters in
# each request, e.g.: https://api.judge0.com/system_info?X-Judge0-User=mySecretToken
# Note that if you enabled authentication, then user should also send valid
# authentication token.

# Specify authorization header name.
# Default: X-Auth-User
AUTHZ_HEADER=

# Specify valid authorization tokens.
# Default: empty - authorization is disabled, protected API calls cannot be issued
AUTHZ_TOKEN=


###############################################################################
# Workers
###############################################################################
# Specify polling frequency in seconds. Decimal numbers are allowed.
# Default: 2
INTERVAL=

# Specify how many parallel workers to run.
# Default: 1
COUNT=

# Specify maximum queue size. Represents maximum number of submissions that
# can wait in the queue at once. If request for new submission comes and the
# queue if full then submission will be rejected.
# Default: 100
MAX_QUEUE_SIZE=


###############################################################################
# Database
###############################################################################
# Specify Redis host
# Default: localhost
REDIS_HOST=

# Specify Redis port.
# Default: 6379
REDIS_PORT=

# Specify Redis password. Cannot be blank.
# Default: NO DEFAULT! MUST BE SET!
REDIS_PASSWORD=YourPasswordHere1234

# Specify Postgres host.
# Default: localhost
POSTGRES_HOST=db

# Specify Postgres port.
# Default: 5432
POSTGRES_PORT=5432

# Name of the database to use. Used only in production.
# Default: postgres
POSTGRES_DB=

# User who can access this database. Used only in production.
# Default: postgres
POSTGRES_USER=

# Password of the user. Cannot be blank. Used only in production.
# Default: NO DEFAULT, YOU MUST SET YOUR PASSWORD
POSTGRES_PASSWORD=YourPasswordHere1234


###############################################################################
# Configuration
###############################################################################
# https://raw.githubusercontent.com/ioi/isolate/master/isolate.1.txt

# If enabled user can request to synchronically wait for submission result on submission create.
# Default: true, i.e. user can request to wait for the result
ENABLE_WAIT_RESULT=

# Default runtime limit for every program (in seconds). Decimal numbers are allowed.
# Time in which the OS assigns the processor to different tasks is not counted.
# Default: 2
CPU_TIME_LIMIT=

# Maximum custom CPU_TIME_LIMIT.
# Default: 15
MAX_CPU_TIME_LIMIT=

# When a time limit is exceeded, wait for extra time (in seconds), before
# killing the program. This has the advantage that the real execution time
# is reported, even though it slightly exceeds the limit.
# Default: 0.5
CPU_EXTRA_TIME=

# Maximum custom CPU_EXTRA_TIME.
# Default: 2
MAX_CPU_EXTRA_TIME=

# Limit wall-clock time in seconds. Decimal numbers are allowed.
# This clock measures the time from the start of the program to its exit,
# so it does not stop when the program has lost the CPU or when it is waiting
# for an external event. We recommend to use CPU_TIME_LIMIT as the main limit,
# but set WALL_TIME_LIMIT to a much higher value as a precaution against
# sleeping programs.
# Default: 5
WALL_TIME_LIMIT=

# Maximum custom WALL_TIME_LIMIT.
# Default: 20
MAX_WALL_TIME_LIMIT=

# Limit address space of the program in kilobytes.
# Default: 128000
MEMORY_LIMIT=

# Maximum custom MEMORY_LIMIT.
# Default: 256000
MAX_MEMORY_LIMIT=

# Limit process stack in kilobytes.
# Default: 64000
STACK_LIMIT=

# Maximum custom STACK_LIMIT.
# Default: 128000
MAX_STACK_LIMIT=

# Maximum number of processes and/or threads program can create.
# Default: 30
MAX_PROCESSES_AND_OR_THREADS=

# Maximum custom MAX_PROCESSES_AND_OR_THREADS.
# Default: 60
MAX_MAX_PROCESSES_AND_OR_THREADS=

# If true then CPU_TIME_LIMIT will be used as per process and thread.
# Default false, i.e. CPU_TIME_LIMIT is set as a total limit for all processes and threads.
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=

# If false, user won't be able to set ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT.
# Default: true
ALLOW_ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=

# If true then MEMORY_LIMIT will be used as per process and thread.
# Default: true, i.e. MEMORY_LIMIT is set as per process and thread.
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=

# If false, user won't be able to set ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT.
# Default: true
ALLOW_ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=

# Limit size of files created (or modified) by the program in kilobytes.
# Default: 1024
MAX_FILE_SIZE=

# Maximum custom MAX_FILE_SIZE.
# Default: 4096
MAX_MAX_FILE_SIZE=

# Run each program this many times and take average of time and memory.
# Default: 1
NUMBER_OF_RUNS=

# Maximum custom NUMBER_OF_RUNS.
# Default: 20
MAX_NUMBER_OF_RUNS=

**Comment by phuongHoang01** [comment]
![image](https://user-images.githubusercontent.com/53004236/66443678-2df56280-ea6a-11e9-84e6-566a1775d8b4.png)

**Comment by hermanzdosilovic** [comment]
Your `REDIS_HOST` should be `redis`.

Do you still experience any problems with this issue?
