### ISSUE TITLE
SaveBtn not working

### ISSUE THREAD

**Issue by kangtegong** [judge0/api#111]
Hello, I was using your https://ide.judge0.com/
but when i try to save the code, this error came out.

```
{
    "readyState": 0,
    "status": 0,
    "statusText": "error"
}
```

Do you have any idea how to fix this?

Thank you for your great work :)
This project really helps me a lot.

**Comment by hermanzdosilovic** [comment]
There was a problem with the server. Judge0 IDE and save button now works as expected. Sorry for inconvenience.
