### ISSUE TITLE
Compilation time limit exceeded

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#114]
@gkapatia in issue #64 reported that for [this code](https://ide.judge0.com/?753ae2f0-512b-4f9c-88b9-553d8b052f06) he sometimes gets and sometimes doesn't an `Compilation time limit exceeded` message in `compile_output` and `Compilation Error` as a status.

He reported that he could see this behaviour on both https://api.judge0.com (v1.4.0) and his own instance of API v1.4.0 (I don't know the what amount of resources he has on this instance).

I can confirm that I have reproduced this problem on https://api.judge0.com after running above code few times. I observed that in 15 runs, the above code reproduced described error exactly once.

Judge0 API v1.4.0 uses [isolate](https://github.com/ioi/isolate) to sandbox compilation and execution. And [here](https://github.com/judge0/api/blob/v1.4.0/app/jobs/isolate_job.rb#L85-L87) you can see that for compilation CPU time limit is set to 5 seconds, CPU extra time is set to 2 seconds and Wall time limit is set to 10 seconds. These numbers are currently hard coded because I estimated that will be enough for almost every compiler. 

**But turns out that if the server load is higher than average at the moment when you compile Java code then these time limits are not enough for Java compiler to finish the compilation in the given time limit.** Take a look at my [question](https://github.com/ioi/isolate/issues/14) for @gollux on this topic from few years ago.

I conclude that this is not really a Judge0 API problem, but server load and scaling problem.

#### Solution 1
Lower the number of parallel workers (config variable `COUNT`) to avoid high server load. I don't know how to estimate what number of workers you need at most for given CPU and memory resources you own. That really depends on the code you are trying to run most of the time. If you mostly expect Java code, then you should lower number of workers. But if you mostly run C, C++, Python or some non-JVM language then number of workers could be higher.

##### My experience
I have 2 CPU/4 GB Digital Ocean droplet on which I run many Judge0 related containers including API and 2 workers. If I could, I would separate workers and API on isolated droplets that run just that. But, I don't have enough money for that. Community help is much appreciated through [Patreon](https://www.patreon.com/hermanzdosilovic) or one time payment through [PayPal](https://www.paypal.com/paypalme2/hermanzdosilovic).

#### Solution 2
Hard code and increase new limits.

#### Solution 3
As for execution time limits, give the user ability to set his own compile limits.

I think that this is a must have long term feature but it will not completely solve the above problem. Because again, if you have more workers than your server can handle or if everybody increase their limits to the max (say 10 or 15 seconds) than this problem would still be present. Same goes for solution 2.

### What to do now
As for current version (v1.4.0) of Judge0 API and public instance of it on https://api.judge0.com there is not much I can do because this service is used by many people all over the world and I don't have enough money to keep it free and well scaled to support so much load along side with other Judge0 related stuff that I run on the same server. You as a community could help me here.

As for your own instance on your own server, think about, play with and investigate solution 1.

**Comment by gkapatia** [comment]
Thanks @hermanzdosilovic for creating the issue. My EC2(AWS) instance have 4 CPU, 8 GB but i was running 5 concurrent worker. will ty to increase resources or decrease workers. Thanks for your help. will comment my findings soon here.

**Comment by chechunaidu** [comment]
can i deploy this code on my server create my own api using this code.if i can how can i do.

**Comment by yashrsharma44** [comment]
@hermanzdosilovic Can you provide some data about how many people currently use the API, when the server hits the bottleneck? I am trying to use judge0 in my personal project for making an online judge for serving around 2000-3000 people, so any suggestions would be welcome

**Comment by hermanzdosilovic** [comment]
Hi @yashrsharma44,
I don't have any information about how many people use public instance of Judge0 API (i.e. https://api.judge0.com).
