### ISSUE TITLE
redundant api attributes

### ISSUE THREAD

**Issue by Bhupesh-V** [judge0/api#116]
I am not sure but some of the API attributes are not visible in a submission response
Attributes :
- `exit_code`
- `exit_signal`
- `created_at`
- `finished_at`

For e.g I am getting a following response
```
{'stdout': None, 'time': '0.043', 'memory': 6592, 'stderr': '  File "main.py", line 3\n    \n                          ^\nSyntaxError: unexpected EOF while parsing\n', 'token': '6b1e1b94-3d3d-4762-91bc-287d976a98ea', 'compile_output': None, 'message': 'Exited with error status 1', 'status': {'id': 11, 'description': 'Runtime Error (NZEC)'}}
```
The above mentioned attributes are missing

**Comment by hermanzdosilovic** [comment]
Hi @Bhupesh-V,

they are not redundant - [link](https://api.judge0.com/submissions/3e46538a-d049-4957-89cc-0eca005f2220?fields=stdout,exit_code,exit_signal,created_at,finished_at). You can choose them with `fields` query parameter.

**Comment by Bhupesh-V** [comment]
Thanks @awasthishubh 
BTW Awesome Service :ok_hand: 
I have made a Python wrapper will soon send a PR
