### ISSUE TITLE
Feature Request/Discussion: MySQL

### ISSUE THREAD

**Issue by saikatharryc** [judge0/api#117]
I'm trying to add MySQL.
The use case I'm looking at is, there will be different SQL dumps. for each question [say].
and for multiple questions, some of the table names might be the same.

so, for this type of use-case, what can be the design strategy, which can also be scalable? 
is it possible to accommodate such use cases even?

**Comment by hermanzdosilovic** [comment]
I am not quite sure how could Judge0 API support MySQL or any other SQL, because it was not intended to do that in the first place. I think this would require a lot of work to be able to support it.

**Comment by catno75** [comment]
There may be a an approached that may work: To use SQLite instead of MySQL.  SQLlite can run inside a python environment and can be created on the fly. That way it could be even possible to create the tables required for a particular test and run the inserts to create the test data either for the session of the test (if that is possible) or even per question, as creating an SQLite, some table and inserts would be very fast so there would be no major overhead even if done per question.

**Comment by saikatharryc** [comment]
That's definitely a good idea to start with I believe.
but there is couple of things, more people use MySQL, and MySQL syntaxes are quite different when you Digg deep. but yeah basic pieces of stuff are the same.

I have tried with one of my project like this though:
I have created one python script, using which I connect to an MYSQL instance create a DB (On the fly, if not exists, that I check from Redis, to make sure not dropping/changing in use database) and add /upsert/update a MySQL user to the database. 
now do all the query with that user, and again the same process if DB does not exist create it.

not sure I'm able to explain properly or not.  let me know if you didn't get this.
this I think is not a good idea, 
what's your opinion on this? can we think or improve this somehow?
@hermanzdosilovic  @catno75

**Comment by hermanzdosilovic** [comment]
For now, I will focus on adding support for SQLite #158. Since this is really a big and complicated feature request I will set it aside for a while.

But you can help me by describing in as many details as you can your use-case and what would you expect from this feature.

**Comment by hermanzdosilovic** [comment]
SQLite is now supported since [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) - try it [here](https://ide.judge0.com/?EU-N).

**Comment by sanjayme97** [comment]
how can i have sqllite compilation  and how can I have database or is there any default database @hermanzdosilovic

**Comment by hermanzdosilovic** [comment]
Take a look a this video https://asciinema.org/a/326975 and let me know if
you need any additional information.

**Comment by sanjayme97** [comment]
then every run(request) we need to send file in base 64 right ? and if user wants to modify database and next request that modification will go as we are sending same file again? @hermanzdosilovic

**Comment by hermanzdosilovic** [comment]
Yes, for every request you need to send a database on which the SQL script will be run.

**Comment by sanjayme97** [comment]
@hermanzdosilovic  Hi I have tried it but l  am getting error like "there is not table " 
I have table demo in file and I have kept file name as db.sqlite and zipped it.
curl --header 'x-rapidapi-key: KEY'      --header 'x-rapidapi-host: judge0.p.rapidapi.com'      --url 'https://judge0.p.rapidapi.com/submissions/8c227363-7db4-41a2-9d43-9ad076882163'
{"stdout":null,"time":"0.009","memory":3008,"stderr":"Error: near line 1: no such table: demo\n","token":"8c227363-7db4-41a2-9d43-9ad076882163","compile_output":null,"message":"Exited with error status 1","status":{"id":11,"description":"Runtime Error (NZEC)"}}

**Comment by hermanzdosilovic** [comment]
Can you send me the `db.sqlite` and SQL script you are trying to use?

**Comment by sanjayme97** [comment]
> Can you send me the `db.sqlite` and SQL script you are trying to use?

db.sqlite - https://drive.google.com/file/d/1nSxlLcpfQVZ5pb2SQXaoKtLCXw0MyHvQ/view?usp=sharing
script I am writing string "select * from demo"

**Comment by hermanzdosilovic** [comment]
@sanjayme97,

Here is what you need to do in the Bash shell.

```bash
$ files=$(zip - db.sqlite | base64 -w0 -) # Create a .zip archive and Base64 encode it.
$ RAPIDAPI_KEY="xxx" # Set your RapidAPI key
$ curl -X POST -H "Content-Type: application/json" -H "X-RapidAPI-Key: $RAPIDAPI_KEY" -H "X-RapidAPI-Host: judge0.p.rapidapi.com" -d "{\"language_id\": 82, \"source_code\": \"select * from demo\", \"additional_files\": \"$files\"}" "https://judge0.p.rapidapi.com/submissions"
{"token":"a6f61546-35ac-4558-bc31-df5a1a51319b"}
$ curl -H "X-RapidAPI-Key: $RAPIDAPI_KEY" -H "X-RapidAPI-Host: judge0.p.rapidapi.com" "https://judge0.p.rapidapi.com/submissions/a6f61546-35ac-4558-bc31-df5a1a51319b"
```

After the first `curl` command you will get a submission token which you then need to use to check for the submission result with the second `curl` command.

This is all you need to do.

Here is the output of your SQL query:
```
1|SQL Online|for Data Science
2|Chart|LINE-SELECT name, cos(id), sin(id) FROM demo;
3|Short CODE|s* tableName => SELECT * FROM tableName
sf tableName => SELECT columns FROM tableName
sl tableName => SELECT * FROM tableName ORDER BY key DESC LIMIT 100;
ct => CREATE TABLE
ii tableName => INSERT INTO
us tableName => UPDATE SET
uw tableName => UPDATE SET WHERE
df tableName => DELETE FROM
dw tableName => DELETE FROM WHERE
4|SqLite 3.32.3|SQL OnLine on JavaScript
5|MultiVersion|3.28.0 to Last (load on settings)
6|[RightClick] mouse|Opens many additional features
7|Left-Panel, Table|[RightClick] mouse "PopMenu" or [DbClick]
8|Tabs|mouse: [RightClick] , [MiddleClick] , [Wheel] , [LeftClick]
9|SQL Editor|autocomplete: [Ctrl-Space] or [Alt-Space]; run: [Shift-Enter]
10|Size table|Fast scroll million rows
11|Share|Create public link DB
12|ai.Url|https://twitter.com/SqliteOnlineCom
13|ai.Color|#9393ad
14|ai.Image|Blob - png, jpg, gif or String(base64) [DbClick] row
15|SQL|Syntax example library
16|CREATE|CREATE TABLE table_name (col1, col2)
17|SELECT|SELECT * FROM table_name
18|INSERT|INSERT INTO table_name (col1, col2) VALUES ("example","test")
19|UPDATE|UPDATE table_name SET col1="work" WHERE col2="test"
20|DELETE|DELETE FROM table_name
```
