### ISSUE TITLE
Deploying Judge0 API for a Huge Audience

### ISSUE THREAD

**Issue by flozender** [judge0/api#118]
Hi, we are trying to deploy the Judge0 API for our institution and we have about 1800-2000 parallel submissions. On our initial test, we had issues with the compilation of our code on a large number of submissions. Can you guide us on what variables to increase in the _judge0-api.conf_?
We are using the v1.4 production release, with the following server configuration:

{
  "Architecture": "x86_64",
  "CPU op-mode(s)": "32-bit, 64-bit",
  "Byte Order": "Little Endian",
  "CPU(s)": "4",
  "On-line CPU(s) list": "0-3",
  "Thread(s) per core": "1",
  "Core(s) per socket": "4",
  "Socket(s)": "1",
  "NUMA node(s)": "1",
  "Vendor ID": "GenuineIntel",
  "CPU family": "6",
  "Model": "79",
  "Model name": "Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz",
  "Stepping": "1",
  "CPU MHz": "2099.998",
  "BogoMIPS": "4199.99",
  "Hypervisor vendor": "VMware",
  "Virtualization type": "full",
  "L1d cache": "32K",
  "L1i cache": "32K",
  "L2 cache": "256K",
  "L3 cache": "20480K",
  "NUMA node0 CPU(s)": "0-3",
  "Mem": "15G",
  "Swap": "2.0G"
}

We tried running multiple workers (~50) but it didn't seem to help.

**Comment by hermanzdosilovic** [comment]
Hi @flozender,

Please take a look at issue #114 where I commented and proposed solutions for this problem.

**Comment by flozender** [comment]
Thanks for the quick reply, I have gone through the issue you suggested. Do you think testing with different number of RAILS_MAX_THREADS, COUNT and MAX_QUEUE_SIZE will be sufficient or are there other attributes that we need to change as well? Thanks again.

**Comment by hermanzdosilovic** [comment]
You said that you expect 1800-2000 submissions at once and if you would like to be able to process them all at once using sufficient number of workers (I don't know what that number is) then you should set `MAX_QUEUE_SIZE` to at least 2000. For your system I think you could set `RAILS_MAX_THREADS` to 20 or maybe even higher. Other settings could be left unchanged (expect `COUNT`, you also need to experiment with it as said in #114).

**Comment by flozender** [comment]
Thank you very much. This helped a lot.

**Comment by flozender** [comment]
Hi, I was testing my local API with the various recommendations you provided, and I was able to boost the performance of the API, but I seem to hit a server timeout. I tried increasing/decreasing various attributes but I'm only able to send around 400-500 submissions/second, the others time out. Do you think this is a hardware limitation or is there a workaround to this?  Also, I have enabled "WAIT" = true.

**Comment by hermanzdosilovic** [comment]
If you use `wait=true` i.e. synchronous submissions then the number of submissions you can process in parallel depends just on the `RAILS_MAX_THREADS`. I would suggest that you deploy Judge0 on multiple servers. Take a look at [this letter](https://notes.dosilovic.com/view.html?AD_CRsbVSmhNxaaNXlyaH_YvSRJl) that I wrote for one of the users. @gkapatia this could probably be useful for you too.

**Comment by gkapatia** [comment]
thanks @hermanzdosilovic

**Comment by flozender** [comment]
Thank you @hermanzdosilovic, I will try this and let you know how it goes.

**Comment by flozender** [comment]
Upon increasing my `RAILS_MAX_THREADS`, I get most submissions back with a `500: Internal Server Error` response. What am I doing wrong? Of the 500 submissions I ran, 391 came back with a `500` error status.

**Comment by hermanzdosilovic** [comment]
Send me a file with the log from the API.

You can access API log by first going inside the container:
```
docker-compose exec api bash
```

And after that you tail and follow (`-f` flag) the log:
```
tail -f log/production.log
```

Or you can change `RAILS_ENV` to `development` (don't forget to restart `docker-compose restart` after that change) then you will see error messages in the HTTP response.

**Comment by flozender** [comment]
I set `RAILS_ENV` to `development` and logged the HTTP response. You can find it here: https://pastebin.com/raw/SjMBL46w. Thanks!

**Comment by hermanzdosilovic** [comment]
It seems that too many clients are connected to the database. It seems that you increased `RAILS_MAX_THREADS` even more to the point where database cannot handle it. As I said, that cannot work and your server will effectively be DDOSed by your own students. Please read [the letter](https://notes.dosilovic.com/view.html?AD_CRsbVSmhNxaaNXlyaH_YvSRJl) that I wrote and don't use `wait=true` for so many requests. That is why I have disabled that for public instance of Judge0 API.

**Comment by flozender** [comment]
I understand, thanks for the insight. I will change the application model to support `wait=false` and split the server as you said.

**Comment by yashrsharma44** [comment]
@flozender Hey can you share some insights about how your machine is working with 2GB ram/15GB storage? I have the same use case as yours so your insights would be beneficial.

**Comment by manrajgrover** [comment]
@hermanzdosilovic If possible, please share the letter you have written for the scaling of this system. It is currently not accessible.

**Comment by hermanzdosilovic** [comment]
> > If you use `wait=true` i.e. synchronous submissions then the number of submissions you can process in parallel depends just on the `RAILS_MAX_THREADS`. I would suggest that you deploy Judge0 on multiple servers. Take a look at [this letter](https://notes.dosilovic.com/view.html?AD_CRsbVSmhNxaaNXlyaH_YvSRJl) that I wrote for one of the users. @gkapatia this could probably be useful for you too.
> 
> @hermanzdosilovic The letter is currently not available, can you share it again?

Don't have it any more. It's been 5 years and I believe it is probably not relevant any more.

**Comment by duyviet2101** [comment]
> > > If you use `wait=true` i.e. synchronous submissions then the number of submissions you can process in parallel depends just on the `RAILS_MAX_THREADS`. I would suggest that you deploy Judge0 on multiple servers. Take a look at [this letter](https://notes.dosilovic.com/view.html?AD_CRsbVSmhNxaaNXlyaH_YvSRJl) that I wrote for one of the users. @gkapatia this could probably be useful for you too.
> > 
> > 
> > @hermanzdosilovic The letter is currently not available, can you share it again?
> 
> Don't have it any more. It's been 5 years and I believe it is probably not relevant any more.

@hermanzdosilovic do you have any guidance or resources on how to scale Judge0? Thank you :3

**Comment by hermanzdosilovic** [comment]
Take a look at https://paper.judge0.com
