### ISSUE TITLE
Worker: Cannot rmdir /var/local/lib/isolate/xx: Directory not empty

### ISSUE THREAD

**Issue by keffadi** [judge0/api#123]
Hello,

Getting this error on worker log, Please can you advise ? ( running in kubernetes)

LOG =
[2019-11-29T15:58:20+00:00] Running submission f1ce5784-70c5-4cee-ae73-92b409b4eb4d (65):
2019-11-29T15:58:20.849928927Z isolate --cg -s -b 65 -M /var/local/lib/isolate/65/metadata.txt -t 2.0 -x 0.5 -w 5.0 -k 64000 -p60 --cg-mem=128000 --no-cg-timing -f 1024 -E HOME=/var/local/lib/isolate/65 -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -d /etc:noexec --run -- /bin/bash run < /var/local/lib/isolate/65/stdin.txt > /var/local/lib/isolate/65/stdout.txt 2> /var/local/lib/isolate/65/stderr.txt 
2019-11-29T15:58:20.952711949Z Cannot rmdir /var/local/lib/isolate/65: Directory not empty

API RETURN: 
{"stdout":"5\n","time":"0.016","memory":3608,"stderr":null,"token":"f1ce5784-70c5-4cee-ae73-92b409b4eb4d","compile_output":null,"message":"Cleanup of sandbox 65 failed.","status":{"id":13,"description":"Internal Error"}}

thank you for your work

**Comment by junchiz** [comment]
Hey I met the same error. Any ideas why? I used the 1.4.0 docker-compose file to do the deployment.

**Comment by hermanzdosilovic** [comment]
Hi!

I haven't tried using Judge0 API in Kubernetes so I cannot reproduce this error. Clearly the problem is that worker couldn't delete sandbox files for some reason but I don't know why would that happen.

**Comment by GeorgeBekh** [comment]
It's not limited to kubernetes only. I've got this error just by running `master` version of the project with docker-compose

**Comment by GeorgeBekh** [comment]
Fixed it here https://github.com/judge0/api/pull/126

**Comment by hermanzdosilovic** [comment]
How can I reproduce this error?

**Comment by GeorgeBekh** [comment]
@hermanzdosilovic start the project (master version) with docker-compose and send some invalid C code, e.g. `asdads`

**Comment by GeorgeBekh** [comment]
Actually i'm not sure if it's reproduceable everywhere.

**Comment by keffadi** [comment]
if you have google kubernetes account, i can share my deployement.yml with you

**Comment by hermanzdosilovic** [comment]
I don't have Google K8S account.

Any update on this @keffadi? Does this error still occurs?

**Comment by nilesh-athghara** [comment]
Hey, @hermanzdosilovic I am deploying this using the mentioned deployment procedure (docker) on amazon ec2(ubuntu) and getting the response " clean of sandbox failed".
    message: 'Cleanup of sandbox 81 failed.',
    status: { id: 13, description: 'Internal Error' }
Can you please help?
Thanks for our work.

**Comment by hermanzdosilovic** [comment]
Hi, I cannot reproduce this error on AWS EC2. Can you please be more specific about your configuration on AWS? Alternatively, you could let me log in to your instance - we could have a Skype debug session.

**Comment by nilesh-athghara** [comment]
hi @hermanzdosilovic,
I found out the docker image which I was using (v1.5.0), did not had the fix #126, once I changed the code as discussed in #126. It is working fine.
Thanks a lot for your reply and work.

**Comment by hermanzdosilovic** [comment]
Hi everybody,

I have finally solved this. Here is the correct [patch](https://github.com/judge0/api/commit/514aec53dca8f1fb9f8f153add05c14d263d6624).

This fix will be available in the next release, i.e. Judge0 API v1.6.0.
