### ISSUE TITLE
http://127.0.0.1:3000/workers return empty list

### ISSUE THREAD

**Issue by junchiz** [judge0/api#124]
After requesting this url. Got an empty list `[]`. I deployed with 1.3.1 and 1.4.0 docker-compose file.

**Comment by hermanzdosilovic** [comment]
What Judge0 API version are you using? Did you follow "Deployment Procedure" from the release notes - https://github.com/judge0/api/releases/tag/v1.4.0?

**Comment by sandeep-adireddi** [comment]
i too have this issue in 1.6.0 version i followed exactly the commands in "Deployment Procedure" i even copy pasted them in exact order

**Comment by hermanzdosilovic** [comment]
Hi @sandeep-adireddi,

can you try running at least one submission with the dummy client and then check again if you get the empty list of workers?

**Comment by sandeep-adireddi** [comment]
when i run in dummy client i get this error

###########
0 error
{
    "readyState": 0,
    "status": 0,
    "statusText": "error"
}
#######################
but when i in insomania (REST client similar to postman) my answer is accepted
![Screenshot from 2020-05-05 16-22-39](https://user-images.githubusercontent.com/16081707/81058773-bba80c00-8eec-11ea-9efd-57e7416a928c.png)

**Comment by sandeep-adireddi** [comment]
I figured it out i was unable to get worker information with i run in http . when i run in https then i was able to fetch the worker information
