### ISSUE TITLE
Server returns 500 on C(++) compilation error

### ISSUE THREAD

**Issue by GeorgeBekh** [judge0/api#129]
Right now when you submit some invalid C code the server responds with 500. You can check it with official demo https://api.judge0.com/dummy-client.html

This happens because gcc compilation message contains non UTF-8 characters.

This PR handles such characters and fixes the error - https://github.com/judge0/api/pull/128

**Comment by hermanzdosilovic** [comment]
I have pushed commit with the changes that do the best thing we can currently do to notify user what is the problem. As commented on your PR `force_encoding("UTF-8")` does not solve the problem.

**Comment by hermanzdosilovic** [comment]
This is now resolved with [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01).
