### ISSUE TITLE
nodejs 8 end of life

### ISSUE THREAD

**Issue by Bhupesh-V** [judge0/api#131]
Node 8 is going to reach its end of life on 31 Dec 2019 [Source](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/)
Will `nodejs 8.5.0` be updated ?

**Comment by hermanzdosilovic** [comment]
Hi @Bhupesh-V,

as of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) Node.js is update to version 12.14.0.

BR,
Herman

**Comment by Bhupesh-V** [comment]
> Hi @Bhupesh-V,
> 
> as of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) Node.js is update to version 12.14.0.
> 
> BR,
> Herman

Thanks for the New Languages :smiley: 
Need to update coderunner now
