### ISSUE TITLE
Request Entity Too large Error 413

### ISSUE THREAD

**Issue by Swap76** [judge0/api#133]
When I hit the route https://api.judge0.com/submissions/  with code, input, output
For some code samples, it works perfect but for some code samples the request gets this error 

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.13.10</center>
</body>
</html>
```
But this same code used to work earlier this year

I have looked on the internet they are telling to change the nginx.config as follows
```
server {
    client_max_body_size 100M;
    ...
}
```

What is the most efficient way of solving this please help.

**Comment by hermanzdosilovic** [comment]
I set `client_max_body_size` to `10M`. Will this be enough for you?

**Comment by Swap76** [comment]
@hermanzdosilovic Yes this will surely work for us.

Are you admin for the website? 

If yes then because of this Compiler more than 400 students are getting benefited thanks for that.

**Comment by hermanzdosilovic** [comment]
Yes I am. Really glad to hear that. Please feel free to contact me (by email or phone) if you have any other questions or if you think that I can help you and your students.

**Comment by Swap76** [comment]
@hermanzdosilovic Thanks for the support :-)

I will let you know if we need something. Thanks again 😊
