### ISSUE TITLE
Need Small Technical Help (Judge0 API)

### ISSUE THREAD

**Issue by newerjc** [judge0/api#136]
Firstly, I would like to thank Herman for creating this wonderful open source project which has helped me in doing my R&D.

I recently saw that you have updated your Judge0 API. My issue is that for now I still want to use your old Judge0 API version probably this v1.2.0 (2019-06-17). 

Got it from here,
https://github.com/judge0/api/releases/download/v1.2.0/judge0-api-v1.2.0.zip

So i created my own instance of Judge0 API in the my Cloud VPS and it is working fine (http://ipaddress:3000/).

Now I am stuck at getting the SSL install on Judge0  API. Means i want to convert http://ipaddress:3000/ to https://domain/

I am thinking of using cloudflare SSL and my own domain to make it work. I wanted to know while connecting  cloudflare SSL with my domain do I need to make any extra changes to any config. files like docker-compose.yml or judge0-api.conf or anything else??

Kindly let me know about this.

**Comment by hermanzdosilovic** [comment]
Hi! In a few days I will create an release with instructions for setting up Judge0 API with SSL.

**Comment by newerjc** [comment]
Thanks Herman
