### ISSUE TITLE
CHANGELOG.md extract zip not working

### ISSUE THREAD

**Issue by kailynw** [judge0/api#138]
Not found- 
`wget https://github.com/judge0/api/releases/download/v1.6.0/judge0-api-v1.6.0-https.zip
`

Works-
`wget https://github.com/judge0/api/releases/download/v1.2.0/judge0 api-v1.2.0.zip`

**Comment by hermanzdosilovic** [comment]
Hi,

v1.6.0 is not released yet so I cannot be used yet.
