### ISSUE TITLE
Is there a way to connect to a postgresql database using an Unix Socket?

### ISSUE THREAD

**Issue by arlekinjose** [judge0/api#140]
Something like this in the configuration file:

POSTGRES_SOCK=/cloudsql/{}/.s.PGSQL.5432

**Comment by arlekinjose** [comment]
I seems I have to set up something like this in the ruby database configuration file  database.yml
host: /cloudsql/{}/.s.PGSQL.5432

**Comment by hermanzdosilovic** [comment]
I don't know. Please follow the official guidelines for setting up Judge0 API.
