### ISSUE TITLE
/workers api not working as expected

### ISSUE THREAD

**Issue by gkapatia** [judge0/api#141]
hey @hermanzdosilovic,

so i have 8 core, 32GB server where I am running 1.4.0 version of api. As per my configuration I have setup 8 workers to run but when I have to check health of server using workers api i get following response.

```
[
  {
    "queue": "default",
    "total": 8,
    "available": 13,
    "idle": 12,
    "working": 1,
    "paused": 0,
    "failed": 0
  }
]
```

I tried restarting docker containers but still getting same response. I don't know which data is correct. Could you please help.

**Comment by hermanzdosilovic** [comment]
Hi.

Try stopping all services with `docker-compose down`. Do this also for all workers. After that remove `srv/redis-data` folder and start everything again.
