### ISSUE TITLE
Getting deployment to work on VPS HTTP (Google Compute Engine) without specifying the port (3000)

### ISSUE THREAD

**Issue by ragrag** [judge0/api#147]
Hello, 

I followed the deployment procedure steps, however i can't seem to get it to work without having to use port 3000, (i have HTTP and HTTPS traffic allowed on the firewall rules of Google Compute Engine)

Would appreciate if someone can shed some light on what i can do.

Do i have to use something like nginx to setup a reverse proxy or i am perhaps doing something wrong

**Comment by hermanzdosilovic** [comment]
Hi @ragrag,

in the Docker Compose find a line that has `- "3000:3000"` and replace it with `- "80:3000"`. Now Judge0 API will be available on port 80 and it should work.

Let me know if that helped.
