### ISSUE TITLE
When decoding compiler_output from base64 getting weird characters.

### ISSUE THREAD

**Issue by nitincoolsharma** [judge0/api#150]
What is the best way to decode compiler_output from base64, now I am getting some weird character while decoding

`"main.c: In function âmainâ:
main.c:6:10: warning: missing terminating " character
   printf("hello, %s
          ^
main.c:6:10: error: missing terminating " character
   printf("hello, %s
          ^~~~~~~~~~
main.c:7:1: warning: missing terminating " character
 ", name);
 ^
main.c:7:1: error: missing terminating " character
 ", name);
 ^~~~~~~~~
main.c:8:3: error: expected expression before âreturnâ
   return 0;
   ^~~~~~
main.c:9:1: error: expected â;â before â}â token
 }
 ^"`

**Comment by hermanzdosilovic** [comment]
If you are using JS I would suggest that you do this:
```javascript
function encode(str) {
    return btoa(unescape(encodeURIComponent(str || "")));
}

function decode(bytes) {
    var escaped = escape(atob(bytes || ""));
    try {
        return decodeURIComponent(escaped);
    } catch {
        return unescape(escaped);
    }
}
```

**Comment by nitincoolsharma** [comment]
Thanks @hermanzdosilovic 

I need one more suggestion

1. For getting the output immediately we can send **wait** parameter while creating a submission.
2. We have one GET API also for getting the submission result

Which is better from your side (1 or 2)?

**Comment by hermanzdosilovic** [comment]
If you are using https://api.judge0.com then you cannot use `wait=true` so that leaves you with second option.

Either way, if you have your own instance of Judge0 API deployed then I would still suggest that you use second option because that way you could process more submissions per some time unit.

**Comment by hermanzdosilovic** [comment]
I hope this [asciicast](https://asciinema.org/a/318475) can help you even more.
