### ISSUE TITLE
Add support for Scala

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#153]
From #151. 

Scala [homepage](https://scala-lang.org).

**Comment by OliverwengFiltered** [comment]
This feature will be sponsored by Filtered

**Comment by hermanzdosilovic** [comment]
Hi @OliverwengFiltered,

I have a problem with adding support for Scala. You can read the details [here](https://github.com/ioi/isolate/issues/90).

One solution might be to not use *isolate* for the compilation of Scala programs but that would be a major security risk. I could add this option in the Judge0 API to compile only Scala programs outside of the *isolate* but you should know that I do not recommend doing that since the compilation of untrusted source code [should be treated in the same way](https://github.com/ioi/isolate/issues/15) as execution from the security standpoint.

For now, I propose that we wait until the maintainers of *isolate* respond. I truly believe they can help.

Let me know what you think.

BR,
Herman

**Comment by OliverwengFiltered** [comment]
Hi @hermanzdosilovic 

Thank you for the update. I agree that we should wait for isolate maintainer's response.

What about other languages' progress ?

Thanks
-Oliver

**Comment by hermanzdosilovic** [comment]
For other languages, you can follow the updates on [projects page](https://github.com/judge0/api/projects). Let's keep this thread focused only on this issue.

**Comment by OliverwengFiltered** [comment]
Sounds good, Herman.

Thank you.

**Comment by hermanzdosilovic** [comment]
Hi @OliverwengFiltered,

thanks to [Filtered](https://www.filtered.ai/) for sponsoring this feature for 20 USD.

This language is now available in [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) and you can try it [here](https://ide.judge0.com/?GkHB).
