### ISSUE TITLE
Add support for Swift

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#154]
From #151.

Add support for [Swift](https://swift.org/).

**Comment by catno75** [comment]
This feature will be sponsored by Evalart.

**Comment by hermanzdosilovic** [comment]
Hi @catno75,

Thank you for considering sponsoring this feature. I can release this by the end of May 2020 for a $30 donation.

**Comment by OliverwengFiltered** [comment]
this feature will be sponsored by Filtered

**Comment by hermanzdosilovic** [comment]
Hi @catno75 and @OliverwengFiltered,

thanks to [Evalart](https://evalart.com) and [Filtered](https://www.filtered.ai/) for sponsoring this feature for 30 USD each.

This language is now available in [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) and you can try it [here](https://ide.judge0.com/?0ao2).

**Comment by OliverwengFiltered** [comment]
Hi @hermanzdosilovic ,

for swift seems there are two issue fond so far:
1. if add `import Foundation` at line 1. and run, it throws error.
2. seems all the compile error is not property allocated into "compile_output" property, instead, it's using stdout to display compile error, which seems not ideal.

Any chance to fix them ?

**Comment by hermanzdosilovic** [comment]
I am not compiling explicity with `swiftc` but rather directly calling `swift Main.swift` that is why these errors are shown in stdout. I will fix this. :)

**Comment by hermanzdosilovic** [comment]
This is the fix on [API Base](https://github.com/judge0/api-base/commit/129f79c079b2158a9084e853bfd10c556f13b72c) side. I now need to propagate it through Judge0 API.

**Comment by OliverwengFiltered** [comment]
Thanks for the update, @hermanzdosilovic .

**Comment by hermanzdosilovic** [comment]
With new release [v1.7.1](https://github.com/judge0/api/releases/tag/v1.7.1) this issue should be resolved.
