### ISSUE TITLE
Add support for R

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#155]
From #151.

R [homepage](https://www.r-project.org/)

Known possible issues:
- [isolate PR 85](https://github.com/ioi/isolate/pull/85)

**Comment by OliverwengFiltered** [comment]
this feature will be sponsored.

**Comment by hermanzdosilovic** [comment]
Hi @OliverwengFiltered,

thanks to [Filtered](https://www.filtered.ai/) for sponsoring this feature for 25 USD.

This language is now available in [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) and you can try it [here](https://ide.judge0.com/?Rqq-).

**Comment by OliverwengFiltered** [comment]
Hi @hermanzdosilovic ,

for R compilation, it seems the compile_output is not populated. everything is throwing under stdout.

any chance to populate compile_output correctly ?

**Comment by hermanzdosilovic** [comment]
Seems that R [cannot be compiled](https://stackoverflow.com/questions/14096520/compile-r-script-into-standalone-exe-file) that is why everything you see is under stderr is an error Rscript interpreter gives to you.

**Comment by dgandhi1993** [comment]
Hi @hermanzdosilovic,

How does one input a variable in R?
Both, readline() and scan() aren't working for me.

Please suggest.
