### ISSUE TITLE
Add support for Kotlin

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#156]
From #151. 

Kotlin [homepage](https://kotlinlang.org).

**Comment by OliverwengFiltered** [comment]
this feature will be sponsored.

**Comment by hermanzdosilovic** [comment]
Hi @OliverwengFiltered,

thanks to [Filtered](https://www.filtered.ai/) for sponsoring this feature for 20 USD.

This language is now available in [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) and you can try it [here](https://ide.judge0.com/?N8Ca).

**Comment by OliverwengFiltered** [comment]
Hi @hermanzdosilovic ,

other languages seems not throwing any warning for a normal run, however, the language kotlin seems throwing a warning and populated to compile_output consistently.

Any chance to remove it ?

Thanks

**Comment by hermanzdosilovic** [comment]
I am aware of this but I don't know how to suppress this warning when using `kotlinc`.
