### ISSUE TITLE
Add support for Visual Basic

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#157]
From #151.

Visual Basic [homepage](https://docs.microsoft.com/en-us/dotnet/visual-basic/).

**Comment by OliverwengFiltered** [comment]
this feature will be sponsored.

**Comment by hermanzdosilovic** [comment]
Hi @OliverwengFiltered,

thanks to [Filtered](https://www.filtered.ai/) for sponsoring this feature for 25 USD.

This language is now available in [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) and you can try it [here](https://ide.judge0.com/?oRjX).

**Comment by OliverwengFiltered** [comment]
Hi @hermanzdosilovic ,

for vb,  it seems it throws compile success message under compile_output, which is not consistent to the existing other languages. any chance to remove the success compile message from compile_output but only populate when there is an error ?

Thanks.

**Comment by hermanzdosilovic** [comment]
This is default output of `vbnc` when compiling (`vbnc Main.vb`). The best I can do is `vbnc -nologo -quiet Main.vb` which will generate following compile_output:
```
Assembly 'Main, Version=0.0, Culture=neutral, PublicKeyToken=null' saved successfully to '/tests/vb/Main.exe'.
Compilation successful
Compilation took 00:00:00.6780480
```

Note that if compile_output is not empty it does not mean that compilation failed. You should look at submissions status_id for that.

**Comment by OliverwengFiltered** [comment]
ok, sounds good, I can use status_id for that then.

**Comment by hermanzdosilovic** [comment]
Yes. You should always use status_id. When you want to know the status of the submission. You can open another issue for more clarification about statuses.
