### ISSUE TITLE
Add support for SQLite

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#158]
From #151. 

SQLite [homepage](https://sqlite.org/index.html).

**Comment by OliverwengFiltered** [comment]
this feature will be sponsored.

**Comment by hermanzdosilovic** [comment]
Hi @OliverwengFiltered,

thanks to [Filtered](https://www.filtered.ai/) for sponsoring this feature for 20 USD.

This language is now available in [v1.7.0](https://github.com/judge0/api/releases/tag/v1.7.0) and you can try it [here](https://ide.judge0.com/?EU-N).
