### ISSUE TITLE
issue while deploying in docker swarm

### ISSUE THREAD

**Issue by sandeep-adireddi** [judge0/api#164]
Hi,
i have deployed the api into docker swarm and when i try to post a submission  it gives internal server error
{
  "stdout": null,
  "time": null,
  "memory": null,
  "stderr": null,
  "token": "1135d7e9-9e1a-4067-a198-7069454bae26",
  "compile_output": null,
  "message": "No such file or directory @ rb_sysopen - /box/main.c",
  "status": {
    "id": 13,
    "description": "Internal Error"
  }
}
it is working fine when i deploy using "docker-compose up"
its there any way for me to deploy api in docker-swarm

**Comment by hermanzdosilovic** [comment]
Hi, this is a known issue that has been resolved in the new version v1.6.0.
