### ISSUE TITLE
API call to fetch  languages set in ALLOWED_LANGUAGES_FOR_COMPILER_OPTION

### ISSUE THREAD

**Issue by sandeep-adireddi** [judge0/api#167]
Hi,
I want to pass information of only languages  set in ALLOWED_LANGUAGES_FOR_COMPILER_OPTION to forntend ide for that it can display only them

**Comment by hermanzdosilovic** [comment]
Can a `/config_info` route help? https://api.judge0.com/config_info

**Comment by sandeep-adireddi** [comment]
It would be better if i can get ids also so that forntend app can send me id in a json object and i can store that in database
