### ISSUE TITLE
No  box file found

### ISSUE THREAD

**Issue by lulg** [judge0/api#178]
first I execute this:
 `curl -X POST -H "Content-Type: application/json" -d '{ "source_code": "echo hello, world", "language_id": 46 }' "http://localhost:18037/submissions" | jq -M`
and got 
```
{
  "token": "cede7675-6982-4cb9-b1bc-c171db886747"
}
```

then I Get the result:
`curl http://localhost:18037/submissions/cede7675-6982-4cb9-b1bc-c171db886747`

`{"stdout":null,"time":null,"memory":null,"stderr":null,"token":"cede7675-6982-4cb9-b1bc-c171db886747","compile_output":null,"message":"No such file or directory @ rb_sysopen - /box/script.sh","status":{"id":13,"description":"Internal Error"}}`

where should I got the '/box/script.sh' file?

**Comment by hermanzdosilovic** [comment]
Hi @lulg,

I am not sure what happened there, I cannot reproduce it on https://api.judge0.com. Do you have some more information that could help me reproduce it?

**Comment by lulg** [comment]
I know the reason.  I user docker swarm mode and it dose not support the  "privileged" properties。I change to use docker compose and its ok. Thank you !

**Comment by alex-s-v** [comment]
Hello. Getting the same exact same error. Following instructions on how to host it yourself, then run exactly the same commands as @lulg but in python. Changed nothing, edited nothing.

Result of `uname -srv`
```
Linux 5.10.70-1-MANJARO #1 SMP PREEMPT Thu Sep 30 15:29:01 UTC 2021
```

Command to start docker daemon
```
systemctl start docker
```

Exact commands I used:
```
wget https://github.com/judge0/judge0/releases/download/v1.13.0/judge0-v1.13.0.zip
unzip judge0-v1.13.0.zip

cd judge0-v1.13.0
docker-compose up -d db redis
docker-compose up -d
```

Result of `docker ps`:
```
CONTAINER ID   IMAGE                  COMMAND                  CREATED         STATUS          PORTS                                       NAMES
b2fb9529a473   judge0/judge0:1.13.0   "/api/docker-entrypo…"   2 minutes ago   Up 2 minutes    2358/tcp                                    judge0-v1-workers-1
081e86e359b1   judge0/judge0:1.13.0   "/api/docker-entrypo…"   2 minutes ago   Up 2 minutes    0.0.0.0:2358->2358/tcp, :::2358->2358/tcp   judge0-v1-server-1
a527f686e4d0   postgres:13.0          "docker-entrypoint.s…"   13 days ago     Up 36 minutes   5432/tcp                                    judge0-v1-db-1
88e5574a15a5   redis:6.0              "docker-entrypoint.s…"   13 days ago     Up 36 minutes   6379/tcp                                    judge0-v1-redis-1
```

Code I executed:
```python
import json
from time import sleep
from pprint import pprint

import requests as r

URL = "http://localhost:2358"

headers = {"Content-Type": "application/json"}
data = {
    "source_code": "print('Hello')",
    "language_id": 71
}

resp = r.post(f"{URL}/submissions/?base64_encoded=false&wait=false", headers=headers, json=data)
if resp.status_code == 201:
    res = json.loads(resp.content)
    token = res["token"]
    for _ in range(100):
        resp = r.get(f"{URL}/submissions/{token}?base64_encoded=false&wait=false", headers=headers, json=data)
        d = json.loads(resp.content)
        if d["status"]["description"] != "In Queue":
            break
        sleep(1)
    pprint(d)
else:
    print(f"Failed with: {resp.status_code}")
    print(resp.content)
```

The result I got:
```
{'compile_output': None,
 'memory': None,
 'message': 'No such file or directory @ rb_sysopen - /box/script.py',
 'status': {'description': 'Internal Error', 'id': 13},
 'stderr': None,
 'stdout': None,
 'time': None,
 'token': '79bab070-44a2-45f6-b1f2-3d9b3197d2c3'}
```

**Comment by darlonv** [comment]
> 

Anyone have solved this problem?

I'm facing the same issue, on Ubuntu 20.04. I also tried setting cgroup1 on grub (suggested on [#325 ),](https://github.com/judge0/judge0/issues/325) but no success.
