### ISSUE TITLE
/statistics returns no content

### ISSUE THREAD

**Issue by bummoblizard** [judge0/api#184]
Whenever using statistics api to fetch the server status, it always return no content (204). It works occasionally though. What could be the issue? I'm running it on a GCP instance.

**Comment by hermanzdosilovic** [comment]
Hi @bummoblizard,

I will need to investigate this further.

**Comment by bummoblizard** [comment]
It seems like there’s a 10 minutes cool down period between every query. If I access the api every 10 minutes or less frequently, it works perfectly.

**Comment by hermanzdosilovic** [comment]
Hi @bummoblizard,

this was a bug and I have fixed it in a new release [v1.8.0](https://github.com/judge0/api/releases/tag/v1.8.0).

Thank you for reporting this! :)
