### ISSUE TITLE
Documentation of Extra Edition of Judge0 API

### ISSUE THREAD

**Issue by bummoblizard** [judge0/api#188]
Hi! Since api.judge0.com is no longer publicly accessible, I cannot access the link below to see the available languages in Extra edition of Judge0 API.

What are the difference between Non-Extra and Extra edition of the API? What extra python libraries are included in the build?

These languages are available in Extra Edition of Judge0 API: https://extra.api.judge0.com/languages

_Originally posted by @hermanzdosilovic in https://github.com/judge0/api/issues/161#issuecomment-626219371_

**Comment by hermanzdosilovic** [comment]
Hi @bummoblizard,

Thank you for noticing, I should change the links in README and elsewhere.

Extra Edition is also available on RapidAPI [here](https://rapidapi.com/hermanzdosilovic/api/judge0-extra).

There, you have access to `/languages` route so you can see what are available languages.

These languages are available in Extra Edition of Judge0:

|#|Name|
|:---:|:---:|
|1|Bosque (latest)|
|2|C (Clang 10.0.1)|
|3|C++ (Clang 10.0.1)|
|4|C3 (latest)|
|5|Java (OpenJDK 14.0.1)|
|6|Java Test (OpenJDK 14.0.1, JUnit Platform Console Standalone 1.6.2)|
|7|MPI (OpenRTE 3.1.3) with C (GCC 8.4.0)|
|8|MPI (OpenRTE 3.1.3) with C++ (GCC 8.4.0)|
|9|MPI (OpenRTE 3.1.3) with Python (3.7.7)|
|10|Nim (stable)|
|11|Python for ML (3.7.7)|

And for *Python for ML* you have following libraries available ([link to code snippet](https://ide.judge0.com/?NdX7)): `mlxtend`, `numpy`, `pandas`, `scipy` and `sklearn`. 

All of the above languages you can try on https://ide.judge0.com

Best regards,
Herman

**Comment by bummoblizard** [comment]
Got it! Thanks for the quick response!

I am actually working on an iOS App using the Judge0 API. Check it out here :)
https://apps.apple.com/US/app/id1512938504

Great work you have done!

Ken

**Comment by guttume** [comment]
can we `pyspark` as well?

**Comment by pathakanuj24** [comment]
can we use pytorch or tensorflow?

**Comment by hermanzdosilovic** [comment]
Yes you can, on Judge0 Extra CE check out language with 25: https://judge0.com/extra-ce.
