### ISSUE TITLE
Strict rate limits for free API plan

### ISSUE THREAD

**Issue by ekzhang** [judge0/api#189]
Hi Herman! First off, thank you for making a great, easy-to-use and well-documented product. I developed a free frontend interface tailored to competitive programmers using your API some time ago, and it was very painless.

I noticed though that the free API plan has a rate limit of 1 request per second, which seems strict. The 10000/month quota is generous, but oftentimes I expect requests to come in bursts from the client (rather than the server). Also, I do not think I can pay for the $20/month plan in my particular use case, which is a personal free hobby project. I also do not want to significantly change my codebase given that this particular project is fairly old, and I have moved on.

Would you be open to adjusting the rate limit to something like 60 requests per minute, rather than 1 request per second? This would allow me to continue running my project as a service to the competitive programming community. Of course, I am not a paying customer, so my apologies if this is too demanding of you or difficult to change - it just means that I will need to shut this project down.

**Comment by hermanzdosilovic** [comment]
Hi @ekzhang,

thank you for your suggestion. I have increased the rate limit for the Basic plan to 100 requests per minute on both Judge0 and Judge0 Extra APIs. Love [wkspace](http://wkspace.herokuapp.com), keep up with awesome work! :smiley: 

Best,
Herman

**Comment by Swap76** [comment]
@hermanzdosilovic Thanks for the generosity to increase the limit and making a limit to per minute. 

I was also worried because of the 1 request a second as we use the APIs to host contests for our college students in India. The project is helping all of us a lot :-)

**Comment by hermanzdosilovic** [comment]
@Swap76, please send me an email so we can stay in touch. I would love to hear more about your platform for hosting contests.

**Comment by Swap76** [comment]
@hermanzdosilovic I will love to I will compile whole info and send a detailed mail to you :-)
