### ISSUE TITLE
Add support for multiple inputs

### ISSUE THREAD

**Issue by shalvah** [judge0/api#19]
Currently, when making a new submission, the parameter `input` is a string. This means if I have multiple test cases (which is common in programming challenges), I'd need to make multiple requests. Could we modify the `input`, `expected_output`, and `stdout` to support multiple test cases (up to a reasonable limit, maybe 5)? 

Aside: Really love what you're doing with this @hermanzdosilovic. Wish I could contribute, but unfortunately, I don't know Ruby. Two thumbs up!

**Comment by hermanzdosilovic** [comment]
Hey @shalvah,

Sorry for the delay in responding to this issue, I was quite busy last couple of days.

> Really love what you're doing with this @hermanzdosilovic. Wish I could contribute, but unfortunately, I don't know Ruby. Two thumbs up!

Thanks, it is nice to hear that! :smile: You started this discussion, and I acknowledge and appreciate it as valuable contribution. :smiley:

How would you like to fetch results of each test case? I don't think that just test case limit is the problem, but also HTTP body size. In competitive programming, test cases (both inputs and outputs) can be really large. How should server respond to request that has `n` inputs and `m` expected_outputs? Should we support separated configurations (time limit, memory limit) for each test case?

This feature request has a lot of sense, but it is a lot of work to do and make it right. I think that we are going to see this in Judge0 API v2.0 :smile:

**Comment by shalvah** [comment]
Yes, it seems it's actually a lot of work. Oh well. Maybe sometime before
then I'll pick up Ruby and be able to help out. Thanks!

**Comment by hermanzdosilovic** [comment]
This has been added in v2.0.0
