### ISSUE TITLE
Request Entity Too Large Error

### ISSUE THREAD

**Issue by Swap76** [judge0/api#190]
When I hit the route https://judge0.p.rapidapi.com/submissions  with code, input, output
For some code samples, it works perfect but for some code samples the request gets this error 

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.13.10</center>
</body>
</html>
```
But this same code used to work earlier this year

Was previously solved in #133 but due to shifting to Rapid API the issue has started to occur again

**Comment by hermanzdosilovic** [comment]
Hi @Swap76,

Sorry, I forgot to update Nginx config after migration to RapidAPI.

I have again set the limits to `10M` for both Judge0 and Judge0 Extra.

Please confirm that it's working for you.

Also, please reopen one of the two issues if this happens again.

**Comment by Swap76** [comment]
@hermanzdosilovic Thanks everything works not perfect :-)

Sorry for creating a new issue from next time if it happens again will reopen the issue.
