### ISSUE TITLE
Problem in deploying judge0 with HTTP in local machine

### ISSUE THREAD

**Issue by prasanth-creator** [judge0/api#197]
Sir, there is no error with docker images but the instance of judge0 is not available in the IP address. the browser displays "The site can't be reached"

**Comment by prasanth-creator** [comment]
Can someone help me to fix this problem. i didn't get any error while installing the docker images but the judge0 instance is not running in the ip address.

**Comment by The-Neo-Noir** [comment]
You did not mention the os you are running the docker on. Usually localhost will be the server is on mac machine.But if docker is not installed correctly it could be problem, accessing localhost that maps to the docker

**Comment by hermanzdosilovic** [comment]
I have a feeling that @prasanth-creator is trying to run Judge0 on Windows, but I haven't tested it on it and don't have any documentation for it.

I would suggest that you @prasanth-creator use free plan on [RapidAPI](https://rapidapi.com/hermanzdosilovic/api/judge0) to explore features of Judge0 or deploy it to AWS, Digital Ocean, etc. on some Linux based host.
