### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by cesar** [judge0/api#2]
Greetings,

Is there going to be upcoming support for other programming languages, specifically JavaScript (thru NodejS)?

**Comment by hermanzdosilovic** [comment]
Hi, no problem. Which versions of NodeJS would you like to see in the next Judge0 API release?

**Comment by cesar** [comment]
I think the latest LTS (NodeJS v6.10.0) would be great! Is there a scheduled time on the next release? How can I help? (Don't know much Ruby, but I'm willing to learn in order to help)

**Comment by hermanzdosilovic** [comment]
I currently don't have scheduled time for the next release, but let's say I will do my best to add NodeJS by the end of this month. If you want you can add NodeJS by yourself, read how [here](https://github.com/judge0/api#adding-new-compiler-or-interpreter).

**Comment by cesar** [comment]
Hey, I added a [PR](https://github.com/judge0/api-base/pull/1) to add support for NodeJS v6 to the api-base image, let me know if this helps.

**Comment by cesar** [comment]
Also added [PR](https://github.com/judge0/api/pull/3) to add support for these languages to the api

**Comment by hermanzdosilovic** [comment]
@cesar I have merged and deployed your changes! Thanks a lot for your contribution :smiley:
