### ISSUE TITLE
How to deploy https with only ip address of the server

### ISSUE THREAD

**Issue by shivaluma** [judge0/api#200]
Im  currently using v1.9.0 with https and deploy it on a compute virtual machine of gcp. The http work well but the https is 500 internal server error and the ssl is not authorized.
in the virtual and letsencrypt host i put the ip of the server. How can i fix this?
Thank you.

**Comment by Aleksei115** [comment]
Hello, do you solve this issue? if you did it, how did you solve it? I have the same issue.
