### ISSUE TITLE
Server Rqeuirements for 50 Users

### ISSUE THREAD

**Issue by MISHRASHIVAM77** [judge0/api#202]
I ran an instance with 1 core and 4 GB Ram. What should be the instance conf if I want 50 users to access the api and compile programs in parallel?

With the above instance, CPU Usage reached 100% when 20 people were accessing the api and compiling every 5-7 seconds.

Is there any config changes required if I want to scale it up for 100 users?

**Comment by gouseferoz** [comment]
I would suggest you increase the processors. If you are just running the judge on the server, 1GB will also be enough with the default configuration provided in the judge.conf file.

**Comment by MISHRASHIVAM77** [comment]
Any suggestion on number of processors based on requests or users.

**Comment by gouseferoz** [comment]
Try 2 or more and see how it behaves in such a load. As you mentioned 20 users will compile every 5-7 seconds, try more than 2.
And which hosting are you using?

**Comment by MISHRASHIVAM77** [comment]
Thanks a lot for such a quick response. I will try and see how it behaves.
I am using Ubuntu 18.04 on AWS.
