### ISSUE TITLE
Add support for header libraries in C

### ISSUE THREAD

**Issue by sanc91** [judge0/api#203]
Header libraries like math, string are providing errors while the same libraries work for C++. 

Error message for math function for a simple sqrt function in C

/usr/bin/ld: /tmp/cccUHC2j.o: in function `main':
main.c:(.text+0x15): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status

**Comment by gouseferoz** [comment]
Hi @sanc91 

for math, you need to be passing `-lm` as the compiler options.
