### ISSUE TITLE
Document Request: Add a .NET(C#) library for interacting with Judge0

### ISSUE THREAD

**Issue by StardustDL** [judge0/api#209]
Thanks for your excellent work! Judge0 helps me a lot to develop an online-judge.

Since I'm a .NET developer, I find that there are no C# library for interacting with Judge0 in `References`.
Then I wrote a C# library to do that. It has been tested for Judge0 v1.6-v1.9.

There is also an online code editor project with this library.

Maybe this is useful for other .NET developers who want to use Judge0, so I submit this issue.

Here are the links of those repositories.
- judge0-dotnet https://github.com/StardustDL/judge0-dotnet
- StarOJ https://github.com/StardustDL/StarOJ

**Comment by hermanzdosilovic** [comment]
Hi @StardustDL,

thank you very much for your contributions. I have added them to the README. :)
