### ISSUE TITLE
Time don't have same precision

### ISSUE THREAD

**Issue by levibn** [judge0/api#21]
First of all, your job is amazing doing this incredibly project! 
I tried run the judge0/api at my Linux/Ubuntu VPS, and its run amazing, thanks to you and the awesome Docker. Unfortunately, my submission running_time is not as precise as at your API. As you can see:
MINE SELF-HOSTED:

> {
>     "token": "d402a8a5-f742-4eca-bd26-5ca8c5f4221e",
>     "status": {
>         "id": 3,
>         "description": "Accepted"
>     },
>     "stdout": "hello, Judge0\n",
>     "stderr": "",
>     "created_at": "2017-05-17T13:35:19.142Z",
>     "finished_at": "2017-05-17T13:35:21.299Z",
>     **"time": "0.0",**
>     "memory": 196,
>     "number_of_runs": 1,
>     "cpu_time_limit": "1.0",
>     "cpu_extra_time": "0.5",
>     "wall_time_limit": "10.0",
>     "memory_limit": 128000,
>     "stack_limit": 128000,
>     "max_processes_and_or_threads": 15,
>     "enable_per_process_and_thread_time_limit": true,
>     "enable_per_process_and_thread_memory_limit": true,
>     "max_file_size": 1024
> }

AT api.judge0.com:

> {
>     "token": "ea55675b-4603-4100-b572-b1fcb112065c",
>     "status": {
>         "id": 3,
>         "description": "Accepted"
>     },
>     "stdout": "hello, Judge0\n",
>     "stderr": "",
>     "created_at": "2017-05-17T13:25:37.808Z",
>     "finished_at": "2017-05-17T13:25:38.116Z",
>     **"time": "0.001",**
>     "memory": 128,
>     "number_of_runs": 1,
>     "cpu_time_limit": "1.0",
>     "cpu_extra_time": "0.5",
>     "wall_time_limit": "10.0",
>     "memory_limit": 128000,
>     "stack_limit": 128000,
>     "max_processes_and_or_threads": 15,
>     "enable_per_process_and_thread_time_limit": true,
>     "enable_per_process_and_thread_memory_limit": true,
>     "max_file_size": 1024
> }

I hope find someone that help me with this issue, so that I can come to contribute in the future with the judge0,

**Comment by levibn** [comment]
Sorry, i check again, doing a for loop, to delay my code and time precision was AMAZING! 

> {
>     "token": "6106ed57-1547-4039-a274-9efc6328650a",
>     "status": {
>         "id": 3,
>         "description": "Accepted"
>     },
>     "stdout": "hello, Judge0\n",
>     "stderr": "",
>     "created_at": "2017-05-17T13:50:01.937Z",
>     "finished_at": "2017-05-17T13:50:02.449Z",
>     **"time": "0.003"**,
>     "memory": 212,
>     "number_of_runs": 1,
>     "cpu_time_limit": "1.0",
>     "cpu_extra_time": "0.5",
>     "wall_time_limit": "10.0",
>     "memory_limit": 128000,
>     "stack_limit": 128000,
>     "max_processes_and_or_threads": 15,
>     "enable_per_process_and_thread_time_limit": true,
>     "enable_per_process_and_thread_memory_limit": true,
>     "max_file_size": 1024
> }

**Comment by hermanzdosilovic** [comment]
> First of all, your job is amazing doing this incredibly project!

Thanks, I appreciate that! :smile: 

> I tried run the judge0/api at my Linux/Ubuntu VPS, and its run amazing, thanks to you and the awesome Docker.

Docker is amazing and I am really glad it was easy for you to setup Judge0 API.

> Unfortunately, my submission running_time is not as precise as at your API.

Running time and precision depends a lot about machine on which you are running code, thus you shouldn't expect it to be the same or even close to the one on [api.judge0.com](https://api.judge0.com).

It is also worth noting that you even don't expect running time to be consistent. Take a look at [ide.judge0.com](http://ide.judge0.com) and try running, for example, hello world program in C++. I have run that three times and these were my running times: 0.002s, 0.002s, 0.001s. This could be a problem if you are building some online judge that uses Judge0 API, and in that case you want to have consistent running times. You could achieve that using [`number_of_runs`](https://api.judge0.com/#header-14.-) attribute when creating submission. Setting this attribute to `10` for example, Judge0 API will run your code 10 times and take an average of time and memory. Using this attribute you could achieve more consistent running time of your program. :smiley:
