### ISSUE TITLE
Broken link to installation instructions in README

### ISSUE THREAD

**Issue by mejibyte** [judge0/api#214]
Hi there,

It looks like the installation instructions link on the README is broken:

![judge0_api__The_most_advanced_open-source_online_code_execution_system_in_the_world_](https://user-images.githubusercontent.com/9726/89136100-cfacdb00-d4e6-11ea-967c-3ecc857c909b.png)

Are there up-to-date installation instructions anywhere? Judge0 looks great and I would love to install it locally and play around with it to understand better how it works.

Thanks a lot!

**Comment by hermanzdosilovic** [comment]
Thank you for noticing. Try following this instructions: https://github.com/judge0/api#get-started

**Comment by mejibyte** [comment]
Thanks, that's great!
