### ISSUE TITLE
Is it possible to be implement it on server without RapidAPI?

### ISSUE THREAD

**Issue by rajkumar-telu** [judge0/api#217]
What exactly do we need to provide at  {VIRTUAL_HOST: 
      - LETSENCRYPT_HOST: 
      - LETSENCRYPT_EMAIL: } ??
As we want to be independent of RapidAPI.

**Comment by gouseferoz** [comment]
@rajkumar-telu If you want to deploy the server with HTTPS then we should be filling the above details.

VIRTUAL_HOST = hostname ex: example.com or subdomain.example.com
LETSENCRYPT_HOST = hostname ex: example.com or subdomain.example.com
LETSENCRYPT_EMAIL = your email id for getting the SSL certificate from LetsEncrypt

**Comment by rajkumar-telu** [comment]
> @rajkumar-telu If you want to deploy the server with HTTPS then we should be filling the above details.
> 
> VIRTUAL_HOST = hostname ex: example.com or subdomain.example.com
> LETSENCRYPT_HOST = hostname ex: example.com or subdomain.example.com
> LETSENCRYPT_EMAIL = your email id for getting the SSL certificate from LetsEncrypt

Hey but is it possible now to implement this as Judge0 and RapidAPI have some agreement it only works through that?
Kindly respond

**Comment by gouseferoz** [comment]
You want to implement the Judge0 as a separate instance for you.

**Comment by rajkumar-telu** [comment]
Yes!

**Comment by gouseferoz** [comment]
https://github.com/judge0/api/releases

Herman has listed out the Deployment Procedure. Please follow that to create your own instance of Judge.
I can help you out if you face any roadblocks with the deployment.

And where are you trying to host your server in?

**Comment by rajkumar-telu** [comment]
Hey feroz syed! Should install docker at our server for this?
Kindly reply

**Comment by gouseferoz** [comment]
Yes, you need to be installing docker. You need to follow the steps listed over there to have a quick judge server of your own.

Or else we can catch up to get this thing working. How can i reach you?

**Comment by rajkumar-telu** [comment]
Hey! I have installed docker on aws server and it went fine till

docker-compose up -d db redis
sleep 10s

But since the third command docker-compose up -d

It's showing error


Searches related to ERROR: failed to register layer: Error processing
tar file(exit status 1): write
/usr/local/ghc-8.8.1/lib/ghc-8.8.1/bin/ghc-iserv-prof: no space left
on device
My linkedin profile : https://www.linkedin.com/in/rajkumar-telukuntla-3477a5165/

**Comment by rajkumar-telu** [comment]
judge0-v1100-https_db_1 is up-to-date
judge0-v1100-https_redis_1 is up-to-date

but when docker-compose up -d command is runned 
I'm out of space on AWS 
Can you tell me how much memory is exactly needed

**Comment by gouseferoz** [comment]
I was able to deploy the server in a basic droplet of digital ocean like 25GB droplet

**Comment by hermanzdosilovic** [comment]
Hi @rajkumar-telu,

you need at least 20GB of disc space.
