### ISSUE TITLE
connection refused 

### ISSUE THREAD

**Issue by hosseinmh** [judge0/api#26]
hello dear 

your website again go to trouble 

thanks

**Comment by hermanzdosilovic** [comment]
Hey, sorry for that. Again, some serious issues with our server. We are going to be up in a hour or two. I will let you know when this happens.

**Comment by hosseinmh** [comment]
thnaks bro

**Comment by hermanzdosilovic** [comment]
Judge0 API is live again! I have also setup UptimeRobot page on https://status.judge0.com/.
