### ISSUE TITLE
Strict whitespace

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#30]
When comparing `stdout` and `expected_stdout` Judge0 API is ignoring additional whitespace at each line.

For example:
let stdout:
```
<space><space><new line>
  *<space><new line>
 ***<space><space><new line>
*****<space><new line>
 ***<space><new line>
  *<space><new line>
<space><new line>
<new line>
<new line>
```

and expected_stdout:
```
<new line>
  *<space><new line>
 ***<new line>
*****<new line>
 ***<new line>
  *<new line>
```

then these two are considered equal, because if you remove all newlines from below and all space from right you get (for both):
```
<new line>
  *<new line>
 ***<new line>
*****<new line>
 ***<new line>
  *<new line>
```

This feature is great because users don't need to worry about aditional `\n` at the end of the output. It happend to me many times that adding `printf("\n");` at the end gave me AC.

But I would like to introduce new feature: `STRICT_WHITESPACE` which wouldn't do these transformations and examples from above would not be the same and accepted.

I need to add:
1. New configuration variable in judge0-api.conf.default called `STRICT_WHITESPACE` which is `false` by default.
2. New attribute for `Submission` model called `strict_whitespace`.

Maybe this attribute can be called more appropriately than `strict_whitespace`. Should think about that.

**Comment by kristijanbartol** [comment]
Another idea for naming: `PRESERVED_WHITESPACE`?

**Comment by hermanzdosilovic** [comment]
Maybe even `PRESERVE_WHITESPACE`.

**Comment by hermanzdosilovic** [comment]
I think that right now this feature is not needed.
