### ISSUE TITLE
Checkers

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#32]
Some tasks can have multiple solutions. When that is the case you need to use special program called *checker* that checks if user's solution is acceptable. Example would be printing one route in a graph from point A to point B - there could be more acceptable solutions.

I would like to add this feature in Judge0 API in the following way. Submission has_one checker (Submission) and checker (Submission) belongs to some submission. Checker is also submission that runs after initial submission is run. But checker is special type of submission that gets three arguments: `stdout`, `stdin` and `expected_output`. It then needs to check if for `stdout` is acceptable for `stdin` when `expected_output` is solution.

Checker would probably inherit all submission's config (`cpu_time_limit`, etc.) and needs to output `1` if submission is acceptable or `0` if it's not (WA). Checker can be written in any language that Judge0 API supports. It is a special type of submission that validates some other submission. Checker queue should be run by different kind of workers.

I should also add new states for submission that has checkers. For example: `In Check Queue` when it's checker is `In Queue` and `Checking` when its checker is `Processing`. Checker would have also his statuses just like submission.

**Comment by kristijanbartol** [comment]
If I understood you would have a checker for each possible correct solution, is this the use case? If yes, why would you want it, i.e. don't you always want to check for all the possible correct solutions at once, not having separate pieces?

**Comment by hermanzdosilovic** [comment]
Noup,
lets say that task is: for given `r` output `O=2*r*pi`. Acceptable solution is in `10^-6`. Checker would check if this is correct for user's output.

**Comment by kristijanbartol** [comment]
Currently the only way to assert against the correct value is through the IDE?

**Comment by andrey-skat** [comment]
@hermanzdosilovic do you have any estimates for that feature?

**Comment by hermanzdosilovic** [comment]
@andrey-skat it is already implemented but not yet released. It will be released in a month or so.

**Comment by andrey-skat** [comment]
> @andrey-skat it is already implemented but not yet released. It will be released in a month or so.

Great! Is there branch or fork to test it before release?

**Comment by hermanzdosilovic** [comment]
It is in a master branch, but please wait for the release and the docs.

**Comment by andrey-skat** [comment]
> It is in a master branch, but please wait for the release and the docs.

@hermanzdosilovic Is it ready to use? :)

**Comment by hermanzdosilovic** [comment]
Hi @andrey-skat,

it can be used in the terms for using multi-file program feature or additional files feature of Judge0. After your code has been run you need to create another submission that will contain your checker code as source code, then, input, expected output and users output as additional files. Then your checker would read those files and tell you if the users solution is OK or not.

Thus, checkers are not implemented as you would expect by giving another source code alongside the submission details, but rather you can have checkers as another submission that has additional files provided as user's output, official input and expected output.

**Comment by andrey-skat** [comment]
@hermanzdosilovic, I have another question :) 
When we send multi-file programs, we always should set language_id to 89. So I sent ruby program with `run` script that looks like `ruby prog.rb`. In response I got error `stderr": "run: line 1: ruby: command not found\n`.

How to make available all languages in multi-file programs?

**Comment by hermanzdosilovic** [comment]
@andrey-skat, all languages are installed under `/usr/local/` ([details](https://ide.judge0.com/?Bzfh)). So instead of `ruby` use `/usr/local/ruby-2.7.0/bin/ruby` ([example](https://ide.judge0.com/?kOU-)).
