### ISSUE TITLE
URL callback

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#33]
It would be cool to have url callback when submission is done.

I need to add following callback attributes:
* `callback_url`
* `callback_verb`
* `callback_fields`
* `callback_format` (json or xml)

Callbacks need to be processed in separate workers.

Think about what other attributes you could add for callbacks.

**Comment by hermanzdosilovic** [comment]
This is now available in [v1.6.0](https://github.com/judge0/api/releases/tag/v1.6.0).

**Comment by jagansankara** [comment]
How can we pass authentication information to callback url? Do we have any option to add custom headers? @hermanzdosilovic
