### ISSUE TITLE
Submission batch create

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/api#34]
Think about this. Why and how.

**Comment by saikatharryc** [comment]
Why:
 this will be useful to say when you have multiple test cases and need to check against that. 
These days I'm doing it with for loop.

**Comment by ragrag** [comment]
any updates on this one ;D?

**Comment by hermanzdosilovic** [comment]
This is now available in [v1.6.0](https://github.com/judge0/api/releases/tag/v1.6.0).
