### ISSUE TITLE
Can system support mutil test cases

### ISSUE THREAD

**Issue by Smith-Curise** [judge0/api#37]
Some acm questions have test data. Now system only support one Stdin and one out. Can we support mutil test cases just like https://www.hackerrank.com/api/docs

**Comment by hermanzdosilovic** [comment]
This subject was already in discussion in this [issue](https://github.com/judge0/api/issues/19). I still think that this feature is unnecessary. If you are building for example online judge than you surely have some model like: `problem` - `has many` - `test cases`; `problem` - `has many` - `submissions`; `submission` - `has many` - `submission results`; `submission result` - `has one` - `test case`. 

Somebody has to implement this `submission` - `has many` - `results`. Online judges surely will implement this, but Judge0 API doesn't need to.

In Judge0 API idea behind `Submission` model is that it represents **one** code rune on given test data. And for that code run you are given results.

The best I could do is to support batch submission create - but I have to think about that before my final decision.

What is your use-case? What are you building with Judge0 API that needs this feature? What are the problems that you have which this feature would solve? How are you solving your problem right now? What are the pros and cons of your current approach?

**Comment by Smith-Curise** [comment]
ok, maybe i can divide one request into multiple requests
