### ISSUE TITLE
problem in production mode 

### ISSUE THREAD

**Issue by hosseinmh** [judge0/api#40]
hello. 
I try to make judge0 in production mode in server , redis server and db server and worker is run but 
root_api_1  is not run and try to restart in many times .
thanks to help me

**Comment by hermanzdosilovic** [comment]
Hi @hosseinmh,

can you please tell me what Compose file are you using and how did you run everything in production environment.

Thanks.

**Comment by hermanzdosilovic** [comment]
If you use `docker-compose.prod.yml` then change `image: postgres` to `image: postgres:9.6.5`. Let me know if that helped.

**Comment by hosseinmh** [comment]
hi 
I do same as instruction  in production mode 
and run using docker-compose up -d and check docker ps the  api and db is restarting 
thanks a lot :)

<img width="1440" alt="screen shot 2017-11-28 at 9 35 56 pm" src="https://user-images.githubusercontent.com/12621753/33336106-2d230ab8-d484-11e7-905c-d3dbf901aaae.png">
