### ISSUE TITLE
Custom online judge that connects to Judge0 API

### ISSUE THREAD

**Issue by mfarahmand98** [judge0/api#42]
Hi
I'm trying to create a programming judge using Django and I came across your website. I was wondering if it is possible to create a Django app which can connect to your API, judge the submission and grade the code?
Thank you

**Comment by hermanzdosilovic** [comment]
Hi @mfarahmand98,

Yes it is! That's why I created Judge0 API! :smiley:

Please subscribe to [Judge0 Website](https://judge0.com) and [watch this project](https://github.com/judge0/api/subscription) for any API changes.

Let me know if I can help you more with your project!

**Comment by mfarahmand98** [comment]
It'd be awesome if you could guide me through this. I read the documentation on the API, but I don't know where to get a token from or where to send the requests mentioned in the documentation.

**Comment by hermanzdosilovic** [comment]
For [official instance of Judge0 API](https://api.judge0.com) you don't need any authentication tokens.

Here are two Python examples of how to create a request:
```python
import requests

url = "https://api.judge0.com/submissions"

payload = "{\"source_code\":\"#include <stdio.h>\\n\\nint main(void) {\\n  char name[10];\\n  scanf(\\\"%s\\\", name);\\n  printf(\\\"hello, %s\\\\n\\\", name);\\n  return 0;\\n}\",\"language_id\":\"4\",\"stdin\":\"Judge0\"}"
headers = {
    'accept': "application/json",
    'content-type': "application/json"
    }

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

and

```python
import http.client

conn = http.client.HTTPSConnection("api.judge0.com")

payload = "{\"source_code\":\"#include <stdio.h>\\n\\nint main(void) {\\n  char name[10];\\n  scanf(\\\"%s\\\", name);\\n  printf(\\\"hello, %s\\\\n\\\", name);\\n  return 0;\\n}\",\"language_id\":\"4\",\"stdin\":\"Judge0\"}"

headers = {
    'accept': "application/json",
    'content-type': "application/json"
    }

conn.request("POST", "/submissions", payload, headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
```

Both examples show how to [create new submission](https://api.judge0.com/#submissions-submission-post).

After creating submission you will get **submission** token. With this token you can check status of your submission using [this call](https://api.judge0.com/#submissions-submission-get).

**Comment by mfarahmand98** [comment]
Got it, thanks. Had misunderstood the whole concept 😅

**Comment by hermanzdosilovic** [comment]
Please reopen this issue if you need any more help.
