### ISSUE TITLE
Return doesn't work

### ISSUE THREAD

**Issue by meetzaveri** [judge0/api#43]
I don't know but why does `stdout` displays null when my response arrives. My source code is - `function hello(hey){return hey + ',hello';} hello('JAY');`.

And when I use `console.log` then it works `function hello(hey){console.log( hey + ',hello');} hello('JAY');`.

Thank You

**Comment by hermanzdosilovic** [comment]
Hi @meetzaveri,

`stdout` attribute represents output of your program to the [standard output](http://www.linfo.org/standard_output.html).

[`console.log`](https://developer.mozilla.org/en-US/docs/Web/API/Console/log) method does just that - outputs an string representation of each given object to standard output (stdout). That is why it works when you use `console.log` method. Here is another way you could output `JAY,hello` to the standard output using this method: https://ide.judge0.com/?AHM4XnjcCfgr8IXwCpidZ4wX8s8l

When you simply return `hello('JAY')` you are returning string `JAY,hello` to the caller. But your actually didn't write anything to the standard output and that is why you get `null` in the `stdout` attribute.

If you have [node](https://nodejs.org/en/) installed on your machine you can try the same thing there:
1) Save the source code you want to run in `hello.js` file
2) In your CLI type: `node hello.js`.

Let me know if I can help you more! :smiley:

**Comment by meetzaveri** [comment]
@hermanzdosilovic Oh got it, so its stdout which is simply for output logging. Thanks for your explanation. And you have made a useful utility for the devs like us! Kudos
