### ISSUE TITLE
Package management support

### ISSUE THREAD

**Issue by kokhans** [judge0/api#44]
Add possibility to use external libraries from package repositories (NuGet, npm, etc).

**Comment by hermanzdosilovic** [comment]
Hi @kokhans,

for the public API - https://api.judge0.com that is not currently planned. If you really need this feature you can install external libraries, wrap everything in new Docker image and deploy this new image.

I could make a tutorial for this in the near future.

BR,
Herman

**Comment by kokhans** [comment]
I'll be much grateful for the tutorial.
And thanks for Judge0.
Great work!

**Comment by gimme4free** [comment]
Hey @hermanzdosilovic 
Did you make the tutorial?
I'd love to learn how to add external libraries too.

Thanks for creating judge0 by the way:)
