### ISSUE TITLE
judge0.com domain and all sub-domains are down

### ISSUE THREAD

**Issue by IrfanBaqui** [judge0/api#46]
Noticed they've been down since a few hours now. Any ETA for a fix - anything I can help with?

**Comment by hermanzdosilovic** [comment]
Hi @IrfanBaqui,

I am aware of that problem. https://status.judge0.com/ confirms that. I had some server issues which included power outage and I hope it will be resolved by the end of this day.

Thanks!

BR,
Herman

**Comment by hermanzdosilovic** [comment]
We will have to wait till Wednesday, anything happening before that would be a miracle. After this outage I decided to move everything to Digital Ocean for better stability. This won't happen again I promise. Really sorry to everyone affected with this issue. :disappointed:

**Comment by IrfanBaqui** [comment]
Hey @hermanzdosilovic, sounds good. Thanks for the update! I can personally vouch for Digital Ocean, so great move there 👍  I love and really appreciate your work, Herman.

Best
Irfan

**Comment by hermanzdosilovic** [comment]
Hey @IrfanBaqui. Judge0 API and IDE are now up and running on Digital Ocean! Enjoy! :smiley:

**Comment by IrfanBaqui** [comment]
Thanks @hermanzdosilovic!
