### ISSUE TITLE
Empty language list

### ISSUE THREAD

**Issue by balababa** [judge0/api#47]
Hi, first sorry for the noob question.
I tried to build a local api server on run it on the local ide project,
I followed the instructions in readme and it can be seen on localhost:3000,
then I changed the  BASE_URL in judge0/ide/js/ide.js to
`BASE_URL = localStorageGetItem("baseUrl") || "http://localhost:3000";`
to test it, but I got 422 response after clicking the run button in any language in the list,
so I checked localhost:3000/languages and it's a empty set [].
Is there any step I missed?thx.

**Comment by hermanzdosilovic** [comment]
Hi @balababa,

take a look at this issue https://github.com/judge0/api/issues/45.

Let me know if that helped.

BR,
Herman
