### ISSUE TITLE
New ETA for the API 2.0?

### ISSUE THREAD

**Issue by IrfanBaqui** [judge0/api#48]
Hey @hermanzdosilovic, I'm seeing good development on the dev branch. Any ETA for v2 release? Let me know if there's anything we can help with.

**Comment by IrfanBaqui** [comment]
Sounds good, @hermanzdosilovic. I'm especially interested in the multiple test cases feature of v2. Can you point me to an example where I can see how to submit test cases with a solution and run the solution against the tests?

**Comment by hermanzdosilovic** [comment]
The first example in documentation does what you need. The only think you need to add is `output` field in each `test case`. Here is an example of request:
```shell
curl --request POST \
  --url https://alpha.v2.api.judge0.com/submissions \
  --header 'Content-Type: application/json' \
  --data '{
  "source": "#include <stdio.h>

int main(void) {
  char name[10];
  scanf(\"%s\", name);
  printf(\"hello, %s\
\", name);
  return 0;
}",
  "language_id": 4,
  "test_cases": [
    {
    	"input": "world",
        "output": "hello, world"
    },
    {
    	"input": "Croatia",
        "output": "hello, Croatia"
    },
    {
    	"input": "Judge0",
        "output": "hello, Judge0"
    }
  ]
}'
```

For the first test case input is `world` and expected output is `hello, world`.

Have I answered your question @IrfanBaqui? Will this example work for you?

**Comment by IrfanBaqui** [comment]
Perfect, that example is enough. Sorry I missed that on Postman.
When you get a chance, can you please push the alpha tag? I'd like to see the changes under the hood and also test it on a local deployment before transitioning to v2.

As always, I really appreciate all the effort!

**Comment by IrfanBaqui** [comment]
Btw, I think the alpha deployment has been broken. The above API call doesn't return a submission id.

**Comment by IrfanBaqui** [comment]
Sounds good @hermanzdosilovic 👍

**Comment by akashgp09** [comment]
>   "test_cases": [
>     {
>         "input": "world",
>         "output": "hello, world"
>     },
>     {
>         "input": "Croatia",
>         "output": "hello, Croatia"
>     },
>     {
>         "input": "Judge0",
>         "output": "hello, Judge0"
>     }
>   ]

Hey @hermanzdosilovic  where can I Read more about the "test_cases" property, I can't find anything related to "test_cases" in the official doc( https://api.judge0.com/ )

**Comment by hermanzdosilovic** [comment]
v2.0 won't be released. There is a feature inside current Judge0 with batch submissions. So please, read that.

**Comment by akashgp09** [comment]
> v2.0 won't be released. There is a feature inside current Judge0 with batch submissions. So please, read that.

@hermanzdosilovic  I read the Submission batch section. From Reading what I know is that it allows to create multiple submissions at once.
But I can't  figure it out how to use the batch submissions feature to **Test my code** with the **actual Output Vs the Expected output.** I would be Very Grateful if you can point me to an Example.

**Comment by hermanzdosilovic** [comment]
@akashgp09 please open a new issue for this topic.
