### ISSUE TITLE
Problem with setup. Rails Error: Unable to access log file.

### ISSUE THREAD

**Issue by Dedock** [judge0/api#5]
Hello, I tried to run your app, I followed all steps but in final step I got that error:
```
Rails Error: Unable to access log file. 
Please ensure that /usr/src/api/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /usr/src/api/log/development.log). 
The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
```

As I understand before executing these steps 
```
$ rails s -b 0.0.0.0
$ rails resque:work QUEUE=* 
```

I have to open new terminal windows and do that 
```
$ ./scripts/dev-shell
```

**Comment by hermanzdosilovic** [comment]
Hello, what system are you using?

**Comment by Dedock** [comment]
OS X Yosemite 10.10.5

**Comment by hermanzdosilovic** [comment]
Please make sure that the username and UID (user id) of your host (OS X Yosemite 10.10.5) matches to the username and UID of the Docker container. More correctly, user who is owner of cloned repository on your host should exist in Docker container.

There are couple of commands which you can run to get your username on both host and Docker container:
```
$ echo $USER
$ whoami
$ id -un
```

and here is how you can get your UID:
```
$ echo $UID
$ id -u
```

Here is what output of these commands look like when I run them on my machine:

Host:
```
[herman@leni api]$ echo $USER
herman
[herman@leni api]$ echo $UID
1000
```

Docker container:
```
herman@3ef0cddec39f:/usr/src/api$ whoami
herman
herman@3ef0cddec39f:/usr/src/api$ id -un
1000
```

**Comment by Dedock** [comment]
I have differenc in last commands. How I can change it?

Host:
iMac-Ludmila-7:api Ludmila$ echo $USER
Ludmila
iMac-Ludmila-7:api Ludmila$ echo $UID
501

Docker container:
Ludmila@c1b997cfc600:/usr/src/api$ whoami
Ludmila
Ludmila@c1b997cfc600:/usr/src/api$ id -un
Ludmila

**Comment by hermanzdosilovic** [comment]
Second command should be `id -u` and not `id -un`. Sorry, I have wrote that wrong in my example (now it is edited and correct).

**Comment by Dedock** [comment]
I have the same outputs.(updated comment) what is probable problem now?

**Comment by hermanzdosilovic** [comment]
Try making `Ludmila` owner of this `log/development.log` file.

Host:
```
iMac-Ludmila-7:api Ludmila$ sudo chown Ludmila log/development.log
```

or in Docker container:
```
Ludmila@c1b997cfc600:/usr/src/api$ sudo chown Ludmila log/development.log
```
---
and make sure that owner of this file has write access:

Host:
```
iMac-Ludmila-7:api Ludmila$ sudo chmod u+w log/development.log
```

or in Docker container:
```
Ludmila@c1b997cfc600:/usr/src/api$ sudo chmod u+w log/development.log
```
