### ISSUE TITLE
Add PHP

### ISSUE THREAD

**Issue by adhavalboy** [judge0/api#51]
Still lots of language not on judge0 API please upgrade with PHP language.I already wrote ide script but json response is not getting plaese add php as soon as possible.

**Comment by JohnPremKumar** [comment]
Yeah, it would be great if PHP was included.

**Comment by GeorgeBekh** [comment]
Here's the PR for that https://github.com/judge0/api-base/pull/5

**Comment by hermanzdosilovic** [comment]
Hi everybody. As of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) PHP is now available.
