### ISSUE TITLE
Error on starting ./scripts/dev-shell

### ISSUE THREAD

**Issue by Rex1911** [judge0/api#54]
I'm on Ubuntu 18.04, and getting the following error on running ./scripts/dev-shell
`useradd: invalid user ID '-m'
ERROR: Service 'api' failed to build: The command '/bin/sh -c useradd -u $DEV_USER_ID -m -r $DEV_USER &&     echo "$DEV_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers &&     echo "set -a" >> /home/$DEV_USER/.bashrc &&     echo "source /usr/src/api/judge0-api.conf" >> /home/$DEV_USER/.bashrc' returned a non-zero code: 3
WARNING: The UID variable is not set. Defaulting to a blank string.
ERROR: No container found for api_1
`

I have no idea whats causing this as I'm completely new to docker

**Comment by hermanzdosilovic** [comment]
Hey @Rex1911,

sorry for the delayed anwser. In [docker-compose.dev.yml](https://github.com/judge0/api/blob/master/docker-compose.dev.yml#L19-L20) change `$USER` with your username, and `$UID` with your user id.

You can get your username from the command line by running one of the following commands:
```
$ whoami
$ echo $USER
```

And you can get your user id from the command line by running:
```
$ echo $UID
```

If `echo $UID` doesn't return anything you could take a look at `/etc/passwd` file and find a line where your username is. The first number you see in that line is your user id. I will probably be `1000`. :)
