### ISSUE TITLE
Java compilation Error

### ISSUE THREAD

**Issue by bikrambhattacharya** [judge0/api#55]
`[Response 05/10/2018, 13:49:02] 201 success
{
    "stdout": null,
    "time": null,
    "memory": null,
    "stderr": null,
    "token": "1368a39d-8b36-41fd-bf03-9c5ded426d5a",
    "compile_output": "Main.java:1: error: class GenerateOTP is public, should be declared in a file named GenerateOTP.java\npublic class GenerateOTP {\n       ^\n1 error\n",
    "message": null,
    "status": {
        "id": 6,
        "description": "Compilation Error"
    }
}`
What should be the class name in order to compile and run java program?

**Comment by hermanzdosilovic** [comment]
Class name should be `Main`.

Here is a hello world program in Java that can be run on Judge0 API:
```java
public class Main {
    public static void main(String[] args) {
        System.out.println("hello, world");
    }
}

```

**Comment by bikrambhattacharya** [comment]
@hermanzdosilovic  Thank you.

**Comment by nyctonio** [comment]
can we only run Main class or there is a method to change the name

**Comment by SumitJainUTD** [comment]
Does the class name has to be Main, Please response, it will save lot of time for us

**Comment by hermanzdosilovic** [comment]
Yes, the class name needs to be `Main`.

**Comment by KedarisettiPrasanth** [comment]
how to make java code execute without any error even with the custom class name?

**Comment by gouseferoz** [comment]
You need to use Main as the class name. Custom class name won't work.

Regards,
Gouse Feroz Syed.
