### ISSUE TITLE
Error while running the Quick Production Setup 

### ISSUE THREAD

**Issue by darrylpinto** [judge0/api#56]
Hi
I tried hosting Judge0 API in production mode following steps 1-6 given in 'Quick Production Setup'.
For the last 2 steps I disabled the -d flag. I am following errors:

`db_1_dd1354599760 | 2018-11-21 22:03:05.784 UTC [61] ERROR:  relation "submissions" does not exist at character 563
db_1_dd1354599760 | 2018-11-21 22:03:05.784 UTC [61] STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
db_1_dd1354599760 | 	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
db_1_dd1354599760 | 	             (SELECT c.collname FROM pg_collation c, pg_type t
db_1_dd1354599760 | 	               WHERE c.oid = a.attcollation AND t.oid = a.atttypid AND a.attcollation <> t.typcollation),
db_1_dd1354599760 | 	                     col_description(a.attrelid, a.attnum) AS comment
db_1_dd1354599760 | 	                FROM pg_attribute a LEFT JOIN pg_attrdef d
db_1_dd1354599760 | 	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
db_1_dd1354599760 | 	               WHERE a.attrelid = '"submissions"'::regclass
db_1_dd1354599760 | 	                 AND a.attnum > 0 AND NOT a.attisdropped
db_1_dd1354599760 | 	               ORDER BY a.attnum`

`db_1_dd1354599760 | 2018-11-21 22:03:07.707 UTC [63] ERROR:  column "increment_by" does not exist at character 95
db_1_dd1354599760 | 2018-11-21 22:03:07.707 UTC [63] STATEMENT:                SELECT setval('"public"."languages_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_by FROM "public"."languages_id_seq"), (SELECT min_value FROM "public"."languages_id_seq")) FROM "languages"), false)
db_1_dd1354599760 | `

`db_1_dd1354599760 | 2018-11-21 22:03:12.251 UTC [66] ERROR:  column "increment_by" does not exist at character 95
db_1_dd1354599760 | 2018-11-21 22:03:12.251 UTC [66] STATEMENT:                SELECT setval('"public"."languages_id_seq"', (SELECT COALESCE(MAX("id")+(SELECT increment_by FROM "public"."languages_id_seq"), (SELECT min_value FROM "public"."languages_id_seq")) FROM "languages"), false)
db_1_dd1354599760 | `

They are mentioned in error.log below
[error.log](https://github.com/judge0/api/files/2605998/error.log)

Do I need to do something else apart from the given steps?

**Comment by keshavagrawal89** [comment]
I m facing the exactly same issue. Is there any update or pointers?

**Comment by keshavagrawal89** [comment]
@darrylpinto I think this is already solved in https://github.com/judge0/api/issues/45 Its the issue with latest postgres image. postgres have changed the way we access increment_by in latest versions.

**Comment by darrylpinto** [comment]
Hi @keshavagrawal89, thank you so much for redirecting me to #45. It solved my issue
