### ISSUE TITLE
Production setup runs into endless loop

### ISSUE THREAD

**Issue by glor** [judge0/api#57]
I followed the instructions under 'Quick Development Setup'
But all containers except redis seam to be stuck in an endless restart loop:
https://asciinema.org/a/9SXQkcstckOkMumkdxDltgpfc

Setup: Manjaro Linux (behaves nearly the same as arch linux), my usual working machine.
Did I do something wrong or is it a bug?

**Comment by glor** [comment]
I could reproduce a similar problem on a different setup (Ubuntu 16.04, relatively fresh installation):
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS               NAMES
593bea5e86b7        judge0/api          "/bin/sh -c 'rm -f..."   27 minutes ago      Restarting (1) 13 minutes ago                       cloud_api_1
dadc04215830        judge0/api          "rails resque:work"      27 minutes ago      Up 27 minutes                   3000/tcp            cloud_worker_1
71166e0c18de        redis               "docker-entrypoint..."   27 minutes ago      Up 27 minutes                   6379/tcp            cloud_redis_1
673a928023a2        postgres            "docker-entrypoint..."   41 minutes ago      Up 41 minutes                   5432/tcp            cloud_db_1
```

**Comment by hermanzdosilovic** [comment]
Hi @glor,

sorry for the delayed response. Please take a look at this issue: https://github.com/judge0/api/issues/56.

**Comment by hermanzdosilovic** [comment]
Can you please do the following:
```
$ docker-compose down
```

And then remove `./srv` folder. Warning! This will delete your Judge0 data you currently have.

And after that try again with the Quick Production Setup.

Please let me know if I can help you more!
