### ISSUE TITLE
sqrt not work with math.h in c

### ISSUE THREAD

**Issue by nguyenvanquan7826** [judge0/api#58]
Hi, I try code with sqrt function, but it show complie error. Please fix it. Thank you.
My code:
```
#include <stdio.h>
#include <math.h>

int main() {
  	float a, b, c, p, s;
  	scanf("%f%f%f", &a, &b, &c);
  	printf("%f", sqrt(a));
}
```
It show:
```
/tmp/ccIcV7Ul.o: In function `main': main.c:(.text+0x30): undefined reference to `sqrt' collect2: error: ld returned 1 exit status
```

**Comment by mduccc** [comment]
I also have the same problem

**Comment by hermanzdosilovic** [comment]
This is because I don't link math library when compiling source code.

Can you maybe use your own Judge0 API instance? I can tell what you need to change to be able to use math lib.
