### ISSUE TITLE
Error In Queue in a long time

### ISSUE THREAD

**Issue by nguyenvanquan7826** [judge0/api#63]
Hi, today I have an error when submit, it show "In Queue" in a long time and it also on https://ide.judge0.com (Running...).
```
[Request 2/8/2019, 9:59:27 AM] GET https://api.judge0.com/submissions/e92fd2e0-bc0a-4895-9908-55aca9b6a735
[Response 2/8/2019, 9:59:28 AM] 200 success
{
    "stdout": null,
    "time": null,
    "memory": null,
    "stderr": null,
    "token": "e92fd2e0-bc0a-4895-9908-55aca9b6a735",
    "compile_output": null,
    "message": null,
    "status": {
        "id": 1,
        "description": "In Queue"
    }
}
```

**Comment by aditya999goel** [comment]
Is it possible to increase number of submissions that can run in parallel from current 5? Also is it feasible to log long waited in-queue jobs on per day basis.

**Comment by hermanzdosilovic** [comment]
@nguyenvanquan7826 I have resolved this problem with long time in the Queue. There was some problem with the workers that is now resolved.

@aditya999goel It would be possible to increase the number of paraller workers from current 5 if I could afford for example $10 or $20 droplet on Digital Ocean.

**Comment by nguyenvanquan7826** [comment]
@hermanzdosilovic yes now it work. But I don't know when it come back "in queue" because before, sometime it work, sometime it "in queue".

**Comment by hermanzdosilovic** [comment]
@nguyenvanquan7826 can you please clarify more your question?

**Comment by nguyenvanquan7826** [comment]
Ah, My mean, before I create this issue, somtime it work, sometime it error "in queue". But now it work ok. Thank you.

**Comment by adityacoder007** [comment]
> paraller workers

Hello,
Could you tell me where you have set number of parallel workers?

Thanks.

**Comment by keerthanasaravanamoorthi** [comment]
Every time submittion  status "In queue".  how to solve this problem.

**Comment by nguyenvanquan7826** [comment]
Hi, today this api error in queue long time again. Please clear or check your server.
