### ISSUE TITLE
Error In Queue again.

### ISSUE THREAD

**Issue by nguyenvanquan7826** [judge0/api#64]
Hi, Today this error come back. Please fix it.

**Comment by hermanzdosilovic** [comment]
Hey @nguyenvanquan7826,

Sorry again. I found what code caused all the problems. I fixed the problem and released Judge0 API v.1.1.0.

This is the code that caused the problem:
```
#include </dev/random>
```

Each submission now has 10 seconds to compile, otherwise compilation is killed and you will get "Compile error" with message "Compilation time limit exceeded.".

Thanks for your report!

**Comment by nguyenvanquan7826** [comment]
Thank!

**Comment by gkapatia** [comment]
hey @hermanzdosilovic, i am seeing this error `Compilation time limit exceeded` lot of time. I am getting this error both at api.judge0.com and the version 1.4.0 that i installed in my server. Could you help regarding this?

**Comment by hermanzdosilovic** [comment]
Can you send the code and language you are trying to run?

**Comment by gkapatia** [comment]
sure! this is token: `753ae2f0-512b-4f9c-88b9-553d8b052f06` at which i got compile-time error
and in this `a1217a15-f710-4ea0-ad01-d0a9ff2bb715` i did not get compile time error

here is java code:
```import java.util.*;
import java.io.*;

class Main{
    public static void main(String[] args)
    {
        Scanner s = new Scanner(System.in);
        long N=s.nextLong();
        if(N==2)
        System.out.println("1");
        
         if(isprime(N))
        System.out.println("0");
        
        else 
        {
            long prime=nextprime(N);
            long d=prime - N;
            System.out.println(d);
        }
        
     }
    
    public static boolean isprime(long N)
    {   
        for(int i=2;i*i<=N;i++)
        {
            if(N%i==0)
            return false;
        }
        
        return true;
        
       }
    public static long nextprime(long N)
    {
        long prime=N;
    int flag = 0;
    while(flag!=1){
        prime+=1;
        if(isprime(prime)){
            flag = 1;
        }
    } 
    return prime;
    }
}```

code is some in both cases, just standard input is different. Thanks

**Comment by hermanzdosilovic** [comment]
@gkapatia I opened a [new issue](https://github.com/judge0/api/issues/114) for this problem. Please, lets continue there.

**Comment by darshan4903** [comment]
I am facing this issue again it was working fine 10-15 days ego but now it is showing IN QUEUE

**Comment by RitikChauhan5132** [comment]
Hi @darshan4903 @hermanzdosilovic  I am also facing same issue it always shows IN QUEUE status when I set up it on my own docker server, can you please share some solution here
I am always getting same issue for all the languages
{
    "source_code": "Y29uc29sZS5sb2coIlNhdmUiKQ==\n",
    "language_id": 63,
    "stdin": "SnVkZ2Uw\n",
    "expected_output": null,
    "stdout": null,
    "status_id": 1,
    "created_at": "2024-04-04T05:22:23.712Z",
    "finished_at": null,
    "time": null,
    "memory": null,
    "stderr": null,
    "token": "0e6a45a9-5167-462f-9dbe-c929e29e1634",
    "number_of_runs": 1,
    "cpu_time_limit": "5.0",
    "cpu_extra_time": "1.0",
    "wall_time_limit": "10.0",
    "memory_limit": 128000,
    "stack_limit": 64000,
    "max_processes_and_or_threads": 60,
    "enable_per_process_and_thread_time_limit": false,
    "enable_per_process_and_thread_memory_limit": false,
    "max_file_size": 1024,
    "compile_output": null,
    "exit_code": null,
    "exit_signal": null,
    "message": null,
    "wall_time": null,
    "compiler_options": null,
    "command_line_arguments": null,
    "redirect_stderr_to_stdout": false,
    "callback_url": null,
    "additional_files": null,
    "enable_network": false,
    "status": {
        "id": 1,
        "description": "In Queue"
    },
    "language": {
        "id": 63,
        "name": "JavaScript (Node.js 12.14.0)"
    }
}

**Comment by darshan4903** [comment]
Hi ,
I can't find any please let me know as well
