### ISSUE TITLE
How to use JavaScript code

### ISSUE THREAD

**Issue by nguyenvanquan7826** [judge0/api#65]
Hi, Could you tell me or example code about JavaScript for read and calculate sum of two number?
In c++ we can use cin to read number, but how to use JavaScript. Thanks!

**Comment by hermanzdosilovic** [comment]
Hi @nguyenvanquan7826,

I took [this](http://rosettacode.org/wiki/A%2BB#JavaScript) example from Rosseta Code. Take a look [here](https://ide.judge0.com/?ACe2-xBtwu7_q_Gp608JtcBqkyRw) to see how it would look like in Judge0 IDE.

**Comment by nguyenvanquan7826** [comment]
Thank you!
