### ISSUE TITLE
Hoe to use Multiple Judge0 Editor on same Page Dynamically

### ISSUE THREAD

**Issue by Radhakrishanan** [judge0/api#66]
I  display Dynamic questions , for each question i want judge0 editor to work  on same page

For Example:
Questions followed by Source Editors dynamically

Issue:
First Question Source Editor Only Enabled and working properly Others not working.

Please let me help with this issue.

**Comment by nguyenvanquan7826** [comment]
I think you must edit your editor or source code of page. It not issue with judge0.

**Comment by hermanzdosilovic** [comment]
Hi @Radhakrishanan,

Do you have an example of this issue? I am not quite sure if I understand the problem.

**Comment by hermanzdosilovic** [comment]
I will close this issue because it is not relevant with Judge0 API.
