### ISSUE TITLE
Is it possible to build api-base say just with Python to reduce the size then use it with api?

### ISSUE THREAD

**Issue by guvenim** [judge0/api#67]
Hi,

I would like to build Judge0 api with just one language, say python 3.6 (for my project I have limited space), then use this docker image with Judge Api?

Sincerely

Guven

**Comment by hermanzdosilovic** [comment]
Hi @guvenim,

I have released Judge0 API v1.1.5 that contains only Python 3.6.8. Take a look at release [here](https://github.com/judge0/api/releases/tag/v1.1.5-python3.6.8).

In release notes you have links to commits in Judge0 API Base and Judge0 API that shows you how you can use just languages that you need.

I hope this helps.

Best regards,
Herman

**Comment by guvenim** [comment]
Dear @hermanzdosilovic 

Thanks a lot for the quick answer and version. it works like a magic:)

Best regards,

Guven
