### ISSUE TITLE
How is it possible to tell the difference between stdout?

### ISSUE THREAD

**Issue by TheOnlyArtz** [judge0/api#71]
Let's say I got this in my main C code
```
printf("AAAA");
printf("BBBB");
```
the stdout will come out like `AAAA BBBB`, how can I tell the difference between each stdout?

**Comment by hermanzdosilovic** [comment]
I don't really understand your question. Can you please be more specific.

**Comment by hermanzdosilovic** [comment]
I will close this issue because is not well defined and explained.
