### ISSUE TITLE
[Feature Request] stdin & expected_output be an array

### ISSUE THREAD

**Issue by kerolloz** [judge0/api#73]
that would help providing multiple stdin and their corresponding expected_output

**Comment by jnfrati** [comment]
I think v2 of the judge API adds that feature so you can have multiple test cases

**Comment by kerolloz** [comment]
@jnfrati 
do you mean this branch? https://github.com/judge0/api/tree/v2/development

**Comment by jnfrati** [comment]
@kerolloz 
I really can't tell what branch is actually the corresponding to v2. But here are some docs about the API [Judge0 v2](https://alpha.v2.api.judge0.com/) It is still on alpha and is not open to the public as it needs authorization token to send submissions and other actions.

**Comment by hermanzdosilovic** [comment]
This is currently in develpment on Judge0 v2 and I can't tell when it will be deployed. You don't need API key for Judge0 v2.

**Comment by kerolloz** [comment]
@hermanzdosilovic 
I can't wait to see judge0 v2 :heart:

**Comment by vcctm** [comment]
This is available btw ?

**Comment by jackbaron** [comment]
any update?
