### ISSUE TITLE
Add Guava and Apache Commons libs to Java classpath

### ISSUE THREAD

**Issue by adityacoder007** [judge0/api#86]
Hi,
It would be nice if you can add Guava and Apache Commons libraries to Java classpath.

Thanks.

**Comment by hermanzdosilovic** [comment]
This is too specific language/library for official release. I can create for you custom Docker image that contains these libraries. Send me an email if you are interested in that.

**Comment by techie-delight** [comment]
I have a suggestion. You can include various libraries with Judge0 API official release, but keep them disabled by default. The user can enable them with judge0.conf file. There are several useful and widely used libraries like boost for C++, Numpy for Python, Guava/Apache libraries for Java, etc. It would be useful to see them working with judge0 api.

**Comment by hermanzdosilovic** [comment]
Numpy is available in [Judge0 Extra](https://rapidapi.com/hermanzdosilovic/api/judge0-extra) and C++ and Java libraries could be sent with multi-file program support in Judge0 v1.10.0.

For now, out of the box solution for external libs won't be supported.
