### ISSUE TITLE
Generate API hits report

### ISSUE THREAD

**Issue by adityacoder007** [judge0/api#87]
How can we generate API hits report like you did here -
https://data.judge0.com/

**Comment by hermanzdosilovic** [comment]
This has been done with https://metabase.com/. You host your own instance of if and then expose one or more dashboards that you create - [example](https://github.com/judge0/data/blob/master/index.html).

**Comment by adityacoder007** [comment]
Thanks. Could you help me with the following info - postgres host, port, Database name, Database username and Database password. These is needed for [Setting Up Metabase](https://metabase.com/docs/v0.32.8/setting-up-metabase.html) instance.

**Comment by hermanzdosilovic** [comment]
Metabase and Postgres containers must be in the same Docker network or Postgres container must expose its `5432` port to public.

I am sending you the simplest example of how can this be done when Metabase and Postgres are implicitly in the same Docker network that Docker Compose created.

1. Download and unzip [this file](https://github.com/judge0/api/files/3298799/judge0-api-v1.2.0-with-metabase.zip).
2. Run `docker-compose up -d && sleep 30s` *Wait 30 seconds for Metabase to initialize.*
3. Open http://localhost:9000 and use following information for connecting to the database:
    - **Host**: `db`
    - **Port**: `5432`
    - **Database name**: `postgres`
    - **Database username**: `postgres`
    - **Database password**: `YourPasswordHere1234`

Note that the information you wrote is the same info from `judge0-api.conf` file (lines: 94, 98, 102, 106, 110).

Hope this helps.
