### ISSUE TITLE
Erro setting up docker-compose.dev.yml while running ./scripts/dev-shell

### ISSUE THREAD

**Issue by mayankshah1607** [judge0/api#89]
I followed the development setup as given in the README.md. After running ./scripts/dev-shell,
it started setting up a docker network. However, it gives me the following error: 

```
ERROR: for judge0-dev-redis  Cannot start service redis: b'driver failed programming external connectivity on endpoint judge0-dev-redis (747e3f6da2e8e7e514d61cf3d689ab5949759e2b93d1f9933d76ae5da8572d8f): Error starting userland proxy: listen tcp 0.0.0.0:6379: bind: address already in use'

```

**Comment by hermanzdosilovic** [comment]
Hi @mayankshah1607,

error says that you already have some application that uses port 6379. Please find what application that could be and close it to make this port free and try again with `./scripts/dev-shell`.
