### ISSUE TITLE
If you have C/C++ from GCC Adding Fortran should be easy

### ISSUE THREAD

**Issue by zbeekman** [judge0/api#90]
Right? If so consider this a feature request 😛

**Comment by hermanzdosilovic** [comment]
Hi @zbeekman,

as of [Judge0 API v1.5.0](https://github.com/judge0/api/blob/master/CHANGELOG.md#v150-2020-01-01) Fortran is now available language.

Best regards,
Herman

**Comment by zbeekman** [comment]
Amazing, thanks so much!!!! 🙇

**Comment by hermanzdosilovic** [comment]
No problem! 😄 [Here](https://ide.judge0.com/?1ZiO) is the example you wrote above.
