### ISSUE TITLE
set paraller workers

### ISSUE THREAD

**Issue by adityacoder007** [judge0/api#91]
Hello,
Could you tell me where you have set number of parallel workers? I have changed the value `COUNT=5` in `judge0-api.conf` but not sure why total and available worker count differs.

`[{"queue":"default","total":5,"available":2,"idle":2,"working":0,"paused":0,"failed":0}]`

Thanks.

**Comment by hermanzdosilovic** [comment]
This has been resolved in Judge0 API v1.2.1.
