### ISSUE TITLE
C/C++/Java

### ISSUE THREAD

**Issue by GalaxyZpj** [judge0/api#92]
I am having difficulty in retrieving the submission data if there are some errors in the program of specified languages. For example, if there are errors in python or javascript, the error is stated in stderr, no such thing happens for c/c++/java, instead the program just stops.

**Comment by hermanzdosilovic** [comment]
Can you please give me some example code for at least one of the mentioned
languages and what do you expect to see? Please give me as much details as
possible so I can better understand the problem and resolve it in the next
release.

**Comment by GalaxyZpj** [comment]
My issue solved. Thanks
