### ISSUE TITLE
API is Down!

### ISSUE THREAD

**Issue by GalaxyZpj** [judge0/api#94]
I just wanna know that is it safe cause i wanna use it in a major project, and I found the API down multiple times on daily basis.

**Comment by hermanzdosilovic** [comment]
I would suggest that you deploy your own instance of Judge0 API for important and time critical applications because public instance of Judge0 API is currently working on $5 Digital Ocean droplet and is being used by many institutions, people and projects all around the world.

**Comment by GalaxyZpj** [comment]
> I would suggest that you deploy your own instance of Judge0 API for important and time critical applications because public instance of Judge0 API is currently working on $5 Digital Ocean droplet and is being used by many institutions, people and projects all around the world.

Could uh suggest how? I am pretty new to this.

**Comment by hermanzdosilovic** [comment]
Every release notes have deployment procedure: https://github.com/judge0/api/releases/tag/v1.2.0. Let me know if you need more instructions or help with deploying.

**Comment by GalaxyZpj** [comment]
> Every release notes have deployment procedure: https://github.com/judge0/api/releases/tag/v1.2.0. Let me know if you need more instructions or help with deploying.

ThankYou.
