### ISSUE TITLE
Request payload storage in database

### ISSUE THREAD

**Issue by adityacoder007** [judge0/api#95]
Hello,
Are you storing request payload in database for each submission? If yes, eventually database will grow huge and might cause out of memory issues in server.

**Comment by hermanzdosilovic** [comment]
Hey @adityacoder007,

Yes, for each submission everything is saved. You are completely right and I have started working on this issue in `v2/development` branch. I don't know when that will be released.

But I can tell you what happens in my production environment for https://api.judge0.com. I currently have almost [3M submissions](https://data.judge0.com/) and my database is ~3.6GB.

If your app (the one which uses Judge0 API) doesn't need to know about all submissions, then you could create a cronjob that deletes really old submissions for database.

**Comment by adityacoder007** [comment]
Thanks for your response.
Also if we delete the existing judge0 docker image and deploy the fresh instance of Judge0 API, that should also resolve the issue.

**Comment by hermanzdosilovic** [comment]
Yes if you are not [persisting postgres data](https://github.com/judge0/api/blob/master/docker-compose.prod.yml#L22) on the local disc. You should delete[ these two lines](https://github.com/judge0/api/blob/master/docker-compose.prod.yml#L21-L22) to not persist database on the disc. And when you delete postgres container, your data will be also deleted.

**Comment by adityacoder007** [comment]
I'm not able to find postgres data directory `/var/lib/postgresql/data/` on my server. Docker is pretty new to me, could you tell me which location to look for?

Also will it impact performance if I opt out of persisting postgres data on the disc?

**Comment by hermanzdosilovic** [comment]
This `/var/lib/postgresql/data` is in Docker container, that is why you cannot find it. On your server database is persisted in `./srv/postgres-data` where `srv` is the folder where `docker-compose.yml` is.

I am not sure about how it will impact performance.

**Comment by adityacoder007** [comment]
> You are completely right and I have started working on this issue in `v2/development` branch. I don't know when that will be released.

Hi Herman,
Any update when the fix would be released? The submissions are considerably increasing disk size each month. It would be nice if users have option to choose if they want submissions data storage in db.

**Comment by hermanzdosilovic** [comment]
Hi @adityacoder007,

in the next release (in about 3 weeks, I hope so) I can create route `DELETE /submissions/<token>`. Would that work for you?

Can you send me by email info about how many data do you generate each month by not deleting submissions? What is your avg test case size, how many submissions per day or month do you have? It will help me decide how to design this data retention for the next releases.
