### ISSUE TITLE
permission denied in worker log

### ISSUE THREAD

**Issue by JohnPremKumar** [judge0/api#96]
Hi,
I have deployed it successfully in development mode for testing.

But after that whatever submission I make. It gives me "Internal error" in description and the output says "no such file or directory Main. java" while running java code

In worker log it showing permission denied need to start it as root

But I cannot sudo inside the docker. While trying with sudo it says "effective uid is not zero or nfs file system mounted without root privileges"

Help me out with this one

**Comment by hermanzdosilovic** [comment]
Can you please describe how did you setup development environment.

**Comment by JohnPremKumar** [comment]
Thanks for the reply.

But anyway, I tried your production setup and everything works fine.

Great project.
