### ISSUE TITLE
Code giving no output

### ISSUE THREAD

**Issue by noisytoken** [judge0/api#99]
Hi

The following code runs successfully but gives no output:

https://ide.judge0.com/?APQIS2M70jXUWZNzAK6dUS7ZEOua

```python
with open("foo.md", "w") as f:
	f.write("hello")	
	
with open("foo.md", "r") as f:
	f.read()
```

**Comment by hermanzdosilovic** [comment]
You need to print what you have read from the file.
https://ide.judge0.com/?ALohaolaUa-0THSVw16UEIVwtH84

The code you give me won't give you the output even on your computer
because you didn't use the print function.

**Comment by noisytoken** [comment]
Okay, got it. 
BTW, I am installing Jugde0.api docker image using the following page:

https://github.com/judge0/api#development-setup

Please tell me how I can copy `judge0-api.conf.default` to `judge0-api.conf`. 

I have already downloaded the image, when I try to start it I get the following output.

```bash
$: sudo docker run -it judge0/api
...
MAX_MAX_FILE_SIZE: 4096
NUMBER_OF_RUNS: 1
MAX_NUMBER_OF_RUNS: 20
Puma starting in single mode...
* Version 3.12.1 (ruby 2.3.3-p222), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```
